/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.jdbc;

import co.edu.sena.model.dao.dao.*;
import co.edu.sena.model.dao.factory.*;
import java.util.Date;
import co.edu.sena.model.dao.dto.*;
import co.edu.sena.model.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class CurrentQuarterDaoImpl extends AbstractDAO implements CurrentQuarterDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id_Current_Quarter, start_Date, end_Date FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id_Current_Quarter, start_Date, end_Date ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id_Current_Quarter = ?, start_Date = ?, end_Date = ? WHERE id_Current_Quarter = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id_Current_Quarter = ?";

	/** 
	 * Index of column id_Current_Quarter
	 */
	protected static final int COLUMN_ID_CURRENT_QUARTER = 1;

	/** 
	 * Index of column start_Date
	 */
	protected static final int COLUMN_START_DATE = 2;

	/** 
	 * Index of column end_Date
	 */
	protected static final int COLUMN_END_DATE = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column id_Current_Quarter
	 */
	protected static final int PK_COLUMN_ID_CURRENT_QUARTER = 1;

	/** 
	 * Inserts a new row in the current_quarter table.
	 */
	public CurrentQuarterPk insert(CurrentQuarter dto) throws CurrentQuarterDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getIdCurrentQuarter() );
			stmt.setDate(index++, dto.getStartDate()==null ? null : new java.sql.Date( dto.getStartDate().getTime() ) );
			stmt.setDate(index++, dto.getEndDate()==null ? null : new java.sql.Date( dto.getEndDate().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CurrentQuarterDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the current_quarter table.
	 */
	public void update(CurrentQuarterPk pk, CurrentQuarter dto) throws CurrentQuarterDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setString( index++, dto.getIdCurrentQuarter() );
			stmt.setDate(index++, dto.getStartDate()==null ? null : new java.sql.Date( dto.getStartDate().getTime() ) );
			stmt.setDate(index++, dto.getEndDate()==null ? null : new java.sql.Date( dto.getEndDate().getTime() ) );
			stmt.setString( 4, pk.getIdCurrentQuarter() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CurrentQuarterDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the current_quarter table.
	 */
	public void delete(CurrentQuarterPk pk) throws CurrentQuarterDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getIdCurrentQuarter() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CurrentQuarterDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the current_quarter table that matches the specified primary-key value.
	 */
	public CurrentQuarter findByPrimaryKey(CurrentQuarterPk pk) throws CurrentQuarterDaoException
	{
		return findByPrimaryKey( pk.getIdCurrentQuarter() );
	}

	/** 
	 * Returns all rows from the current_quarter table that match the criteria 'id_Current_Quarter = :idCurrentQuarter'.
	 */
	public CurrentQuarter findByPrimaryKey(String idCurrentQuarter) throws CurrentQuarterDaoException
	{
		CurrentQuarter ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id_Current_Quarter = ?", new Object[] { idCurrentQuarter } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the current_quarter table that match the criteria ''.
	 */
	public CurrentQuarter[] findAll() throws CurrentQuarterDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id_Current_Quarter", null );
	}

	/** 
	 * Returns all rows from the current_quarter table that match the criteria 'id_Current_Quarter = :idCurrentQuarter'.
	 */
	public CurrentQuarter[] findWhereIdCurrentQuarterEquals(String idCurrentQuarter) throws CurrentQuarterDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_Current_Quarter = ? ORDER BY id_Current_Quarter", new Object[] { idCurrentQuarter } );
	}

	/** 
	 * Returns all rows from the current_quarter table that match the criteria 'start_Date = :startDate'.
	 */
	public CurrentQuarter[] findWhereStartDateEquals(Date startDate) throws CurrentQuarterDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE start_Date = ? ORDER BY start_Date", new Object[] { startDate==null ? null : new java.sql.Date( startDate.getTime() ) } );
	}

	/** 
	 * Returns all rows from the current_quarter table that match the criteria 'end_Date = :endDate'.
	 */
	public CurrentQuarter[] findWhereEndDateEquals(Date endDate) throws CurrentQuarterDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE end_Date = ? ORDER BY end_Date", new Object[] { endDate==null ? null : new java.sql.Date( endDate.getTime() ) } );
	}

	/**
	 * Method 'CurrentQuarterDaoImpl'
	 * 
	 */
	public CurrentQuarterDaoImpl()
	{
	}

	/**
	 * Method 'CurrentQuarterDaoImpl'
	 * 
	 * @param userConn
	 */
	public CurrentQuarterDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "wariosoft.current_quarter";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected CurrentQuarter fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			CurrentQuarter dto = new CurrentQuarter();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected CurrentQuarter[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			CurrentQuarter dto = new CurrentQuarter();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		CurrentQuarter ret[] = new CurrentQuarter[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(CurrentQuarter dto, ResultSet rs) throws SQLException
	{
		dto.setIdCurrentQuarter( rs.getString( COLUMN_ID_CURRENT_QUARTER ) );
		dto.setStartDate( rs.getDate(COLUMN_START_DATE ) );
		dto.setEndDate( rs.getDate(COLUMN_END_DATE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(CurrentQuarter dto)
	{
	}

	/** 
	 * Returns all rows from the current_quarter table that match the specified arbitrary SQL statement
	 */
	public CurrentQuarter[] findByDynamicSelect(String sql, Object[] sqlParams) throws CurrentQuarterDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CurrentQuarterDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the current_quarter table that match the specified arbitrary SQL statement
	 */
	public CurrentQuarter[] findByDynamicWhere(String sql, Object[] sqlParams) throws CurrentQuarterDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CurrentQuarterDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
