/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.dto;

import co.edu.sena.dao.*;
import co.edu.sena.factory.*;
import co.edu.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Activity implements Serializable
{
	/** 
	 * This attribute maps to the column id_Activity in the activity table.
	 */
	protected int idActivity;

	/** 
	 * This attribute maps to the column Name in the activity table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column Code in the activity table.
	 */
	protected String code;

	/** 
	 * This attribute maps to the column name_phase in the activity table.
	 */
	protected String namePhase;

	/**
	 * Method 'Activity'
	 * 
	 */
	public Activity()
	{
	}

	/**
	 * Method 'getIdActivity'
	 * 
	 * @return int
	 */
	public int getIdActivity()
	{
		return idActivity;
	}

	/**
	 * Method 'setIdActivity'
	 * 
	 * @param idActivity
	 */
	public void setIdActivity(int idActivity)
	{
		this.idActivity = idActivity;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getCode'
	 * 
	 * @return String
	 */
	public String getCode()
	{
		return code;
	}

	/**
	 * Method 'setCode'
	 * 
	 * @param code
	 */
	public void setCode(String code)
	{
		this.code = code;
	}

	/**
	 * Method 'getNamePhase'
	 * 
	 * @return String
	 */
	public String getNamePhase()
	{
		return namePhase;
	}

	/**
	 * Method 'setNamePhase'
	 * 
	 * @param namePhase
	 */
	public void setNamePhase(String namePhase)
	{
		this.namePhase = namePhase;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Activity)) {
			return false;
		}
		
		final Activity _cast = (Activity) _other;
		if (idActivity != _cast.idActivity) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (code == null ? _cast.code != code : !code.equals( _cast.code )) {
			return false;
		}
		
		if (namePhase == null ? _cast.namePhase != namePhase : !namePhase.equals( _cast.namePhase )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idActivity;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		if (code != null) {
			_hashCode = 29 * _hashCode + code.hashCode();
		}
		
		if (namePhase != null) {
			_hashCode = 29 * _hashCode + namePhase.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ActivityPk
	 */
	public ActivityPk createPk()
	{
		return new ActivityPk(idActivity, namePhase, code);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.dto.Activity: " );
		ret.append( "idActivity=" + idActivity );
		ret.append( ", name=" + name );
		ret.append( ", code=" + code );
		ret.append( ", namePhase=" + namePhase );
		return ret.toString();
	}

}
