/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the learning_result table.
 */
public class LearningResultPk implements Serializable
{
	protected String code;

	protected String programCode;

	protected String version;

	protected String competitionCode;

	/** 
	 * Sets the value of code
	 */
	public void setCode(String code)
	{
		this.code = code;
	}

	/** 
	 * Gets the value of code
	 */
	public String getCode()
	{
		return code;
	}

	/** 
	 * Sets the value of programCode
	 */
	public void setProgramCode(String programCode)
	{
		this.programCode = programCode;
	}

	/** 
	 * Gets the value of programCode
	 */
	public String getProgramCode()
	{
		return programCode;
	}

	/** 
	 * Sets the value of version
	 */
	public void setVersion(String version)
	{
		this.version = version;
	}

	/** 
	 * Gets the value of version
	 */
	public String getVersion()
	{
		return version;
	}

	/** 
	 * Sets the value of competitionCode
	 */
	public void setCompetitionCode(String competitionCode)
	{
		this.competitionCode = competitionCode;
	}

	/** 
	 * Gets the value of competitionCode
	 */
	public String getCompetitionCode()
	{
		return competitionCode;
	}

	/**
	 * Method 'LearningResultPk'
	 * 
	 */
	public LearningResultPk()
	{
	}

	/**
	 * Method 'LearningResultPk'
	 * 
	 * @param code
	 * @param programCode
	 * @param version
	 * @param competitionCode
	 */
	public LearningResultPk(final String code, final String programCode, final String version, final String competitionCode)
	{
		this.code = code;
		this.programCode = programCode;
		this.version = version;
		this.competitionCode = competitionCode;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof LearningResultPk)) {
			return false;
		}
		
		final LearningResultPk _cast = (LearningResultPk) _other;
		if (code == null ? _cast.code != code : !code.equals( _cast.code )) {
			return false;
		}
		
		if (programCode == null ? _cast.programCode != programCode : !programCode.equals( _cast.programCode )) {
			return false;
		}
		
		if (version == null ? _cast.version != version : !version.equals( _cast.version )) {
			return false;
		}
		
		if (competitionCode == null ? _cast.competitionCode != competitionCode : !competitionCode.equals( _cast.competitionCode )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (code != null) {
			_hashCode = 29 * _hashCode + code.hashCode();
		}
		
		if (programCode != null) {
			_hashCode = 29 * _hashCode + programCode.hashCode();
		}
		
		if (version != null) {
			_hashCode = 29 * _hashCode + version.hashCode();
		}
		
		if (competitionCode != null) {
			_hashCode = 29 * _hashCode + competitionCode.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.dto.LearningResultPk: " );
		ret.append( "code=" + code );
		ret.append( ", programCode=" + programCode );
		ret.append( ", version=" + version );
		ret.append( ", competitionCode=" + competitionCode );
		return ret.toString();
	}

}
