/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the learning_result_has_activity table.
 */
public class LearningResultHasActivityPk implements Serializable
{
	protected int activityIdActivity;

	protected String namePhase;

	protected String projectCode;

	protected String learningResultCode;

	protected String programCode;

	protected String version;

	protected String competitionCode;

	/** 
	 * This attribute represents whether the primitive attribute activityIdActivity is null.
	 */
	protected boolean activityIdActivityNull;

	/** 
	 * Sets the value of activityIdActivity
	 */
	public void setActivityIdActivity(int activityIdActivity)
	{
		this.activityIdActivity = activityIdActivity;
	}

	/** 
	 * Gets the value of activityIdActivity
	 */
	public int getActivityIdActivity()
	{
		return activityIdActivity;
	}

	/** 
	 * Sets the value of namePhase
	 */
	public void setNamePhase(String namePhase)
	{
		this.namePhase = namePhase;
	}

	/** 
	 * Gets the value of namePhase
	 */
	public String getNamePhase()
	{
		return namePhase;
	}

	/** 
	 * Sets the value of projectCode
	 */
	public void setProjectCode(String projectCode)
	{
		this.projectCode = projectCode;
	}

	/** 
	 * Gets the value of projectCode
	 */
	public String getProjectCode()
	{
		return projectCode;
	}

	/** 
	 * Sets the value of learningResultCode
	 */
	public void setLearningResultCode(String learningResultCode)
	{
		this.learningResultCode = learningResultCode;
	}

	/** 
	 * Gets the value of learningResultCode
	 */
	public String getLearningResultCode()
	{
		return learningResultCode;
	}

	/** 
	 * Sets the value of programCode
	 */
	public void setProgramCode(String programCode)
	{
		this.programCode = programCode;
	}

	/** 
	 * Gets the value of programCode
	 */
	public String getProgramCode()
	{
		return programCode;
	}

	/** 
	 * Sets the value of version
	 */
	public void setVersion(String version)
	{
		this.version = version;
	}

	/** 
	 * Gets the value of version
	 */
	public String getVersion()
	{
		return version;
	}

	/** 
	 * Sets the value of competitionCode
	 */
	public void setCompetitionCode(String competitionCode)
	{
		this.competitionCode = competitionCode;
	}

	/** 
	 * Gets the value of competitionCode
	 */
	public String getCompetitionCode()
	{
		return competitionCode;
	}

	/**
	 * Method 'LearningResultHasActivityPk'
	 * 
	 */
	public LearningResultHasActivityPk()
	{
	}

	/**
	 * Method 'LearningResultHasActivityPk'
	 * 
	 * @param activityIdActivity
	 * @param namePhase
	 * @param projectCode
	 * @param learningResultCode
	 * @param programCode
	 * @param version
	 * @param competitionCode
	 */
	public LearningResultHasActivityPk(final int activityIdActivity, final String namePhase, final String projectCode, final String learningResultCode, final String programCode, final String version, final String competitionCode)
	{
		this.activityIdActivity = activityIdActivity;
		this.namePhase = namePhase;
		this.projectCode = projectCode;
		this.learningResultCode = learningResultCode;
		this.programCode = programCode;
		this.version = version;
		this.competitionCode = competitionCode;
	}

	/** 
	 * Sets the value of activityIdActivityNull
	 */
	public void setActivityIdActivityNull(boolean activityIdActivityNull)
	{
		this.activityIdActivityNull = activityIdActivityNull;
	}

	/** 
	 * Gets the value of activityIdActivityNull
	 */
	public boolean isActivityIdActivityNull()
	{
		return activityIdActivityNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof LearningResultHasActivityPk)) {
			return false;
		}
		
		final LearningResultHasActivityPk _cast = (LearningResultHasActivityPk) _other;
		if (activityIdActivity != _cast.activityIdActivity) {
			return false;
		}
		
		if (namePhase == null ? _cast.namePhase != namePhase : !namePhase.equals( _cast.namePhase )) {
			return false;
		}
		
		if (projectCode == null ? _cast.projectCode != projectCode : !projectCode.equals( _cast.projectCode )) {
			return false;
		}
		
		if (learningResultCode == null ? _cast.learningResultCode != learningResultCode : !learningResultCode.equals( _cast.learningResultCode )) {
			return false;
		}
		
		if (programCode == null ? _cast.programCode != programCode : !programCode.equals( _cast.programCode )) {
			return false;
		}
		
		if (version == null ? _cast.version != version : !version.equals( _cast.version )) {
			return false;
		}
		
		if (competitionCode == null ? _cast.competitionCode != competitionCode : !competitionCode.equals( _cast.competitionCode )) {
			return false;
		}
		
		if (activityIdActivityNull != _cast.activityIdActivityNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + activityIdActivity;
		if (namePhase != null) {
			_hashCode = 29 * _hashCode + namePhase.hashCode();
		}
		
		if (projectCode != null) {
			_hashCode = 29 * _hashCode + projectCode.hashCode();
		}
		
		if (learningResultCode != null) {
			_hashCode = 29 * _hashCode + learningResultCode.hashCode();
		}
		
		if (programCode != null) {
			_hashCode = 29 * _hashCode + programCode.hashCode();
		}
		
		if (version != null) {
			_hashCode = 29 * _hashCode + version.hashCode();
		}
		
		if (competitionCode != null) {
			_hashCode = 29 * _hashCode + competitionCode.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (activityIdActivityNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.dto.LearningResultHasActivityPk: " );
		ret.append( "activityIdActivity=" + activityIdActivity );
		ret.append( ", namePhase=" + namePhase );
		ret.append( ", projectCode=" + projectCode );
		ret.append( ", learningResultCode=" + learningResultCode );
		ret.append( ", programCode=" + programCode );
		ret.append( ", version=" + version );
		ret.append( ", competitionCode=" + competitionCode );
		return ret.toString();
	}

}
