/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.dto;

import co.edu.sena.dao.*;
import co.edu.sena.factory.*;
import co.edu.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Project implements Serializable
{
	/** 
	 * This attribute maps to the column Code in the project table.
	 */
	protected String code;

	/** 
	 * This attribute maps to the column Name in the project table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column State in the project table.
	 */
	protected int state;

	/** 
	 * This attribute represents whether the primitive attribute state is null.
	 */
	protected boolean stateNull = true;

	/**
	 * Method 'Project'
	 * 
	 */
	public Project()
	{
	}

	/**
	 * Method 'getCode'
	 * 
	 * @return String
	 */
	public String getCode()
	{
		return code;
	}

	/**
	 * Method 'setCode'
	 * 
	 * @param code
	 */
	public void setCode(String code)
	{
		this.code = code;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getState'
	 * 
	 * @return int
	 */
	public int getState()
	{
		return state;
	}

	/**
	 * Method 'setState'
	 * 
	 * @param state
	 */
	public void setState(int state)
	{
		this.state = state;
		this.stateNull = false;
	}

	/**
	 * Method 'setStateNull'
	 * 
	 * @param value
	 */
	public void setStateNull(boolean value)
	{
		this.stateNull = value;
	}

	/**
	 * Method 'isStateNull'
	 * 
	 * @return boolean
	 */
	public boolean isStateNull()
	{
		return stateNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Project)) {
			return false;
		}
		
		final Project _cast = (Project) _other;
		if (code == null ? _cast.code != code : !code.equals( _cast.code )) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (state != _cast.state) {
			return false;
		}
		
		if (stateNull != _cast.stateNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (code != null) {
			_hashCode = 29 * _hashCode + code.hashCode();
		}
		
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + state;
		_hashCode = 29 * _hashCode + (stateNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProjectPk
	 */
	public ProjectPk createPk()
	{
		return new ProjectPk(code);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.dto.Project: " );
		ret.append( "code=" + code );
		ret.append( ", name=" + name );
		ret.append( ", state=" + state );
		return ret.toString();
	}

}
