/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.dto;

import co.edu.sena.dao.*;
import co.edu.sena.factory.*;
import co.edu.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Schedule implements Serializable
{
	/** 
	 * This attribute maps to the column document_Number in the schedule table.
	 */
	protected String documentNumber;

	/** 
	 * This attribute maps to the column id_Document in the schedule table.
	 */
	protected String idDocument;

	/** 
	 * This attribute maps to the column start_Time in the schedule table.
	 */
	protected String startTime;

	/** 
	 * This attribute maps to the column end_Time in the schedule table.
	 */
	protected String endTime;

	/** 
	 * This attribute maps to the column name_Day in the schedule table.
	 */
	protected String nameDay;

	/** 
	 * This attribute maps to the column modality_Name in the schedule table.
	 */
	protected String modalityName;

	/** 
	 * This attribute maps to the column number_Ambience in the schedule table.
	 */
	protected String numberAmbience;

	/** 
	 * This attribute maps to the column name_Headquarters in the schedule table.
	 */
	protected String nameHeadquarters;

	/** 
	 * This attribute maps to the column number_Ficha in the schedule table.
	 */
	protected String numberFicha;

	/** 
	 * This attribute maps to the column quarter_Name in the schedule table.
	 */
	protected String quarterName;

	/** 
	 * This attribute maps to the column acronyms_Working_Day in the schedule table.
	 */
	protected String acronymsWorkingDay;

	/** 
	 * This attribute maps to the column idVersion in the schedule table.
	 */
	protected int idVersion;

	/** 
	 * This attribute maps to the column idCurrent_Quarter in the schedule table.
	 */
	protected String idcurrentQuarter;

	/**
	 * Method 'Schedule'
	 * 
	 */
	public Schedule()
	{
	}

	/**
	 * Method 'getDocumentNumber'
	 * 
	 * @return String
	 */
	public String getDocumentNumber()
	{
		return documentNumber;
	}

	/**
	 * Method 'setDocumentNumber'
	 * 
	 * @param documentNumber
	 */
	public void setDocumentNumber(String documentNumber)
	{
		this.documentNumber = documentNumber;
	}

	/**
	 * Method 'getIdDocument'
	 * 
	 * @return String
	 */
	public String getIdDocument()
	{
		return idDocument;
	}

	/**
	 * Method 'setIdDocument'
	 * 
	 * @param idDocument
	 */
	public void setIdDocument(String idDocument)
	{
		this.idDocument = idDocument;
	}

	/**
	 * Method 'getStartTime'
	 * 
	 * @return String
	 */
	public String getStartTime()
	{
		return startTime;
	}

	/**
	 * Method 'setStartTime'
	 * 
	 * @param startTime
	 */
	public void setStartTime(String startTime)
	{
		this.startTime = startTime;
	}

	/**
	 * Method 'getEndTime'
	 * 
	 * @return String
	 */
	public String getEndTime()
	{
		return endTime;
	}

	/**
	 * Method 'setEndTime'
	 * 
	 * @param endTime
	 */
	public void setEndTime(String endTime)
	{
		this.endTime = endTime;
	}

	/**
	 * Method 'getNameDay'
	 * 
	 * @return String
	 */
	public String getNameDay()
	{
		return nameDay;
	}

	/**
	 * Method 'setNameDay'
	 * 
	 * @param nameDay
	 */
	public void setNameDay(String nameDay)
	{
		this.nameDay = nameDay;
	}

	/**
	 * Method 'getModalityName'
	 * 
	 * @return String
	 */
	public String getModalityName()
	{
		return modalityName;
	}

	/**
	 * Method 'setModalityName'
	 * 
	 * @param modalityName
	 */
	public void setModalityName(String modalityName)
	{
		this.modalityName = modalityName;
	}

	/**
	 * Method 'getNumberAmbience'
	 * 
	 * @return String
	 */
	public String getNumberAmbience()
	{
		return numberAmbience;
	}

	/**
	 * Method 'setNumberAmbience'
	 * 
	 * @param numberAmbience
	 */
	public void setNumberAmbience(String numberAmbience)
	{
		this.numberAmbience = numberAmbience;
	}

	/**
	 * Method 'getNameHeadquarters'
	 * 
	 * @return String
	 */
	public String getNameHeadquarters()
	{
		return nameHeadquarters;
	}

	/**
	 * Method 'setNameHeadquarters'
	 * 
	 * @param nameHeadquarters
	 */
	public void setNameHeadquarters(String nameHeadquarters)
	{
		this.nameHeadquarters = nameHeadquarters;
	}

	/**
	 * Method 'getNumberFicha'
	 * 
	 * @return String
	 */
	public String getNumberFicha()
	{
		return numberFicha;
	}

	/**
	 * Method 'setNumberFicha'
	 * 
	 * @param numberFicha
	 */
	public void setNumberFicha(String numberFicha)
	{
		this.numberFicha = numberFicha;
	}

	/**
	 * Method 'getQuarterName'
	 * 
	 * @return String
	 */
	public String getQuarterName()
	{
		return quarterName;
	}

	/**
	 * Method 'setQuarterName'
	 * 
	 * @param quarterName
	 */
	public void setQuarterName(String quarterName)
	{
		this.quarterName = quarterName;
	}

	/**
	 * Method 'getAcronymsWorkingDay'
	 * 
	 * @return String
	 */
	public String getAcronymsWorkingDay()
	{
		return acronymsWorkingDay;
	}

	/**
	 * Method 'setAcronymsWorkingDay'
	 * 
	 * @param acronymsWorkingDay
	 */
	public void setAcronymsWorkingDay(String acronymsWorkingDay)
	{
		this.acronymsWorkingDay = acronymsWorkingDay;
	}

	/**
	 * Method 'getIdVersion'
	 * 
	 * @return int
	 */
	public int getIdVersion()
	{
		return idVersion;
	}

	/**
	 * Method 'setIdVersion'
	 * 
	 * @param idVersion
	 */
	public void setIdVersion(int idVersion)
	{
		this.idVersion = idVersion;
	}

	/**
	 * Method 'getIdcurrentQuarter'
	 * 
	 * @return String
	 */
	public String getIdcurrentQuarter()
	{
		return idcurrentQuarter;
	}

	/**
	 * Method 'setIdcurrentQuarter'
	 * 
	 * @param idcurrentQuarter
	 */
	public void setIdcurrentQuarter(String idcurrentQuarter)
	{
		this.idcurrentQuarter = idcurrentQuarter;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Schedule)) {
			return false;
		}
		
		final Schedule _cast = (Schedule) _other;
		if (documentNumber == null ? _cast.documentNumber != documentNumber : !documentNumber.equals( _cast.documentNumber )) {
			return false;
		}
		
		if (idDocument == null ? _cast.idDocument != idDocument : !idDocument.equals( _cast.idDocument )) {
			return false;
		}
		
		if (startTime == null ? _cast.startTime != startTime : !startTime.equals( _cast.startTime )) {
			return false;
		}
		
		if (endTime == null ? _cast.endTime != endTime : !endTime.equals( _cast.endTime )) {
			return false;
		}
		
		if (nameDay == null ? _cast.nameDay != nameDay : !nameDay.equals( _cast.nameDay )) {
			return false;
		}
		
		if (modalityName == null ? _cast.modalityName != modalityName : !modalityName.equals( _cast.modalityName )) {
			return false;
		}
		
		if (numberAmbience == null ? _cast.numberAmbience != numberAmbience : !numberAmbience.equals( _cast.numberAmbience )) {
			return false;
		}
		
		if (nameHeadquarters == null ? _cast.nameHeadquarters != nameHeadquarters : !nameHeadquarters.equals( _cast.nameHeadquarters )) {
			return false;
		}
		
		if (numberFicha == null ? _cast.numberFicha != numberFicha : !numberFicha.equals( _cast.numberFicha )) {
			return false;
		}
		
		if (quarterName == null ? _cast.quarterName != quarterName : !quarterName.equals( _cast.quarterName )) {
			return false;
		}
		
		if (acronymsWorkingDay == null ? _cast.acronymsWorkingDay != acronymsWorkingDay : !acronymsWorkingDay.equals( _cast.acronymsWorkingDay )) {
			return false;
		}
		
		if (idVersion != _cast.idVersion) {
			return false;
		}
		
		if (idcurrentQuarter == null ? _cast.idcurrentQuarter != idcurrentQuarter : !idcurrentQuarter.equals( _cast.idcurrentQuarter )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (documentNumber != null) {
			_hashCode = 29 * _hashCode + documentNumber.hashCode();
		}
		
		if (idDocument != null) {
			_hashCode = 29 * _hashCode + idDocument.hashCode();
		}
		
		if (startTime != null) {
			_hashCode = 29 * _hashCode + startTime.hashCode();
		}
		
		if (endTime != null) {
			_hashCode = 29 * _hashCode + endTime.hashCode();
		}
		
		if (nameDay != null) {
			_hashCode = 29 * _hashCode + nameDay.hashCode();
		}
		
		if (modalityName != null) {
			_hashCode = 29 * _hashCode + modalityName.hashCode();
		}
		
		if (numberAmbience != null) {
			_hashCode = 29 * _hashCode + numberAmbience.hashCode();
		}
		
		if (nameHeadquarters != null) {
			_hashCode = 29 * _hashCode + nameHeadquarters.hashCode();
		}
		
		if (numberFicha != null) {
			_hashCode = 29 * _hashCode + numberFicha.hashCode();
		}
		
		if (quarterName != null) {
			_hashCode = 29 * _hashCode + quarterName.hashCode();
		}
		
		if (acronymsWorkingDay != null) {
			_hashCode = 29 * _hashCode + acronymsWorkingDay.hashCode();
		}
		
		_hashCode = 29 * _hashCode + idVersion;
		if (idcurrentQuarter != null) {
			_hashCode = 29 * _hashCode + idcurrentQuarter.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SchedulePk
	 */
	public SchedulePk createPk()
	{
		return new SchedulePk(documentNumber, idDocument, nameDay, numberAmbience, nameHeadquarters, numberFicha, quarterName, acronymsWorkingDay, idVersion, idcurrentQuarter);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.dto.Schedule: " );
		ret.append( "documentNumber=" + documentNumber );
		ret.append( ", idDocument=" + idDocument );
		ret.append( ", startTime=" + startTime );
		ret.append( ", endTime=" + endTime );
		ret.append( ", nameDay=" + nameDay );
		ret.append( ", modalityName=" + modalityName );
		ret.append( ", numberAmbience=" + numberAmbience );
		ret.append( ", nameHeadquarters=" + nameHeadquarters );
		ret.append( ", numberFicha=" + numberFicha );
		ret.append( ", quarterName=" + quarterName );
		ret.append( ", acronymsWorkingDay=" + acronymsWorkingDay );
		ret.append( ", idVersion=" + idVersion );
		ret.append( ", idcurrentQuarter=" + idcurrentQuarter );
		return ret.toString();
	}

}
