/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.dto;

import co.edu.sena.dao.*;
import co.edu.sena.factory.*;
import co.edu.sena.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Speciality implements Serializable
{
	/** 
	 * This attribute maps to the column speciality_Name in the speciality table.
	 */
	protected String specialityName;

	/** 
	 * This attribute maps to the column Status in the speciality table.
	 */
	protected short status;

	/**
	 * Method 'Speciality'
	 * 
	 */
	public Speciality()
	{
	}

	/**
	 * Method 'getSpecialityName'
	 * 
	 * @return String
	 */
	public String getSpecialityName()
	{
		return specialityName;
	}

	/**
	 * Method 'setSpecialityName'
	 * 
	 * @param specialityName
	 */
	public void setSpecialityName(String specialityName)
	{
		this.specialityName = specialityName;
	}

	/**
	 * Method 'getStatus'
	 * 
	 * @return short
	 */
	public short getStatus()
	{
		return status;
	}

	/**
	 * Method 'setStatus'
	 * 
	 * @param status
	 */
	public void setStatus(short status)
	{
		this.status = status;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Speciality)) {
			return false;
		}
		
		final Speciality _cast = (Speciality) _other;
		if (specialityName == null ? _cast.specialityName != specialityName : !specialityName.equals( _cast.specialityName )) {
			return false;
		}
		
		if (status != _cast.status) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (specialityName != null) {
			_hashCode = 29 * _hashCode + specialityName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) status;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SpecialityPk
	 */
	public SpecialityPk createPk()
	{
		return new SpecialityPk(specialityName);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.dto.Speciality: " );
		ret.append( "specialityName=" + specialityName );
		ret.append( ", status=" + status );
		return ret.toString();
	}

}
