/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the trimester_has_learning_result table.
 */
public class TrimesterHasLearningResultPk implements Serializable
{
	protected String quarterName;

	protected String acronymsWorkingDay;

	protected String specialityName;

	protected String learningResultCode;

	protected String programCode;

	protected String competitionCode;

	protected String version;

	/** 
	 * Sets the value of quarterName
	 */
	public void setQuarterName(String quarterName)
	{
		this.quarterName = quarterName;
	}

	/** 
	 * Gets the value of quarterName
	 */
	public String getQuarterName()
	{
		return quarterName;
	}

	/** 
	 * Sets the value of acronymsWorkingDay
	 */
	public void setAcronymsWorkingDay(String acronymsWorkingDay)
	{
		this.acronymsWorkingDay = acronymsWorkingDay;
	}

	/** 
	 * Gets the value of acronymsWorkingDay
	 */
	public String getAcronymsWorkingDay()
	{
		return acronymsWorkingDay;
	}

	/** 
	 * Sets the value of specialityName
	 */
	public void setSpecialityName(String specialityName)
	{
		this.specialityName = specialityName;
	}

	/** 
	 * Gets the value of specialityName
	 */
	public String getSpecialityName()
	{
		return specialityName;
	}

	/** 
	 * Sets the value of learningResultCode
	 */
	public void setLearningResultCode(String learningResultCode)
	{
		this.learningResultCode = learningResultCode;
	}

	/** 
	 * Gets the value of learningResultCode
	 */
	public String getLearningResultCode()
	{
		return learningResultCode;
	}

	/** 
	 * Sets the value of programCode
	 */
	public void setProgramCode(String programCode)
	{
		this.programCode = programCode;
	}

	/** 
	 * Gets the value of programCode
	 */
	public String getProgramCode()
	{
		return programCode;
	}

	/** 
	 * Sets the value of competitionCode
	 */
	public void setCompetitionCode(String competitionCode)
	{
		this.competitionCode = competitionCode;
	}

	/** 
	 * Gets the value of competitionCode
	 */
	public String getCompetitionCode()
	{
		return competitionCode;
	}

	/** 
	 * Sets the value of version
	 */
	public void setVersion(String version)
	{
		this.version = version;
	}

	/** 
	 * Gets the value of version
	 */
	public String getVersion()
	{
		return version;
	}

	/**
	 * Method 'TrimesterHasLearningResultPk'
	 * 
	 */
	public TrimesterHasLearningResultPk()
	{
	}

	/**
	 * Method 'TrimesterHasLearningResultPk'
	 * 
	 * @param quarterName
	 * @param acronymsWorkingDay
	 * @param specialityName
	 * @param learningResultCode
	 * @param programCode
	 * @param competitionCode
	 * @param version
	 */
	public TrimesterHasLearningResultPk(final String quarterName, final String acronymsWorkingDay, final String specialityName, final String learningResultCode, final String programCode, final String competitionCode, final String version)
	{
		this.quarterName = quarterName;
		this.acronymsWorkingDay = acronymsWorkingDay;
		this.specialityName = specialityName;
		this.learningResultCode = learningResultCode;
		this.programCode = programCode;
		this.competitionCode = competitionCode;
		this.version = version;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TrimesterHasLearningResultPk)) {
			return false;
		}
		
		final TrimesterHasLearningResultPk _cast = (TrimesterHasLearningResultPk) _other;
		if (quarterName == null ? _cast.quarterName != quarterName : !quarterName.equals( _cast.quarterName )) {
			return false;
		}
		
		if (acronymsWorkingDay == null ? _cast.acronymsWorkingDay != acronymsWorkingDay : !acronymsWorkingDay.equals( _cast.acronymsWorkingDay )) {
			return false;
		}
		
		if (specialityName == null ? _cast.specialityName != specialityName : !specialityName.equals( _cast.specialityName )) {
			return false;
		}
		
		if (learningResultCode == null ? _cast.learningResultCode != learningResultCode : !learningResultCode.equals( _cast.learningResultCode )) {
			return false;
		}
		
		if (programCode == null ? _cast.programCode != programCode : !programCode.equals( _cast.programCode )) {
			return false;
		}
		
		if (competitionCode == null ? _cast.competitionCode != competitionCode : !competitionCode.equals( _cast.competitionCode )) {
			return false;
		}
		
		if (version == null ? _cast.version != version : !version.equals( _cast.version )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (quarterName != null) {
			_hashCode = 29 * _hashCode + quarterName.hashCode();
		}
		
		if (acronymsWorkingDay != null) {
			_hashCode = 29 * _hashCode + acronymsWorkingDay.hashCode();
		}
		
		if (specialityName != null) {
			_hashCode = 29 * _hashCode + specialityName.hashCode();
		}
		
		if (learningResultCode != null) {
			_hashCode = 29 * _hashCode + learningResultCode.hashCode();
		}
		
		if (programCode != null) {
			_hashCode = 29 * _hashCode + programCode.hashCode();
		}
		
		if (competitionCode != null) {
			_hashCode = 29 * _hashCode + competitionCode.hashCode();
		}
		
		if (version != null) {
			_hashCode = 29 * _hashCode + version.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.dto.TrimesterHasLearningResultPk: " );
		ret.append( "quarterName=" + quarterName );
		ret.append( ", acronymsWorkingDay=" + acronymsWorkingDay );
		ret.append( ", specialityName=" + specialityName );
		ret.append( ", learningResultCode=" + learningResultCode );
		ret.append( ", programCode=" + programCode );
		ret.append( ", competitionCode=" + competitionCode );
		ret.append( ", version=" + version );
		return ret.toString();
	}

}
