/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dao;

import co.edu.sena.model.dao.dto.*;
import co.edu.sena.model.dao.exceptions.*;

public interface LearningOutcomeHasNumberGroupHasTrimesterDao
{
	/** 
	 * Inserts a new row in the learning_outcome_has_number_group_has_trimester table.
	 */
	public LearningOutcomeHasNumberGroupHasTrimesterPk insert(LearningOutcomeHasNumberGroupHasTrimester dto) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Updates a single row in the learning_outcome_has_number_group_has_trimester table.
	 */
	public void update(LearningOutcomeHasNumberGroupHasTrimesterPk pk, LearningOutcomeHasNumberGroupHasTrimester dto) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Deletes a single row in the learning_outcome_has_number_group_has_trimester table.
	 */
	public void delete(LearningOutcomeHasNumberGroupHasTrimesterPk pk) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns the rows from the learning_outcome_has_number_group_has_trimester table that matches the specified primary-key value.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester findByPrimaryKey(LearningOutcomeHasNumberGroupHasTrimesterPk pk) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'l_Outcome_Code = :lOutcomeCode AND competition_Code = :competitionCode AND program_Code = :programCode AND version = :version AND number_Group = :numberGroup AND name_Trimester = :nameTrimester AND initials_Working_Day = :initialsWorkingDay AND training_Level = :trainingLevel'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester findByPrimaryKey(String lOutcomeCode, String competitionCode, String programCode, String version, String numberGroup, String nameTrimester, String initialsWorkingDay, String trainingLevel) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria ''.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findAll() throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'l_Outcome_Code = :lOutcomeCode AND competition_Code = :competitionCode AND program_Code = :programCode AND version = :version'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findByLearningOutcome(String lOutcomeCode, String competitionCode, String programCode, String version) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'number_Group = :numberGroup AND name_Trimester = :nameTrimester AND initials_Working_Day = :initialsWorkingDay AND training_Level = :trainingLevel'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findByNumberGroupHasTrimester(String numberGroup, String nameTrimester, String initialsWorkingDay, String trainingLevel) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'l_Outcome_Code = :lOutcomeCode'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findWhereLOutcomeCodeEquals(String lOutcomeCode) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'program_Code = :programCode'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findWhereProgramCodeEquals(String programCode) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'competition_Code = :competitionCode'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findWhereCompetitionCodeEquals(String competitionCode) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'name_Trimester = :nameTrimester'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findWhereNameTrimesterEquals(String nameTrimester) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'number_Group = :numberGroup'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findWhereNumberGroupEquals(String numberGroup) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'initials_Working_Day = :initialsWorkingDay'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findWhereInitialsWorkingDayEquals(String initialsWorkingDay) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'version = :version'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findWhereVersionEquals(String version) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the criteria 'training_Level = :trainingLevel'.
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findWhereTrainingLevelEquals(String trainingLevel) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the specified arbitrary SQL statement
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findByDynamicSelect(String sql, Object[] sqlParams) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the learning_outcome_has_number_group_has_trimester table that match the specified arbitrary SQL statement
	 */
	public LearningOutcomeHasNumberGroupHasTrimester[] findByDynamicWhere(String sql, Object[] sqlParams) throws LearningOutcomeHasNumberGroupHasTrimesterDaoException;

}
