/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dao;

import co.edu.sena.model.dao.dto.*;
import co.edu.sena.model.dao.exceptions.*;

public interface NumberGroupHasTrimesterDao
{
	/** 
	 * Inserts a new row in the number_group_has_trimester table.
	 */
	public NumberGroupHasTrimesterPk insert(NumberGroupHasTrimester dto) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Updates a single row in the number_group_has_trimester table.
	 */
	public void update(NumberGroupHasTrimesterPk pk, NumberGroupHasTrimester dto) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Deletes a single row in the number_group_has_trimester table.
	 */
	public void delete(NumberGroupHasTrimesterPk pk) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns the rows from the number_group_has_trimester table that matches the specified primary-key value.
	 */
	public NumberGroupHasTrimester findByPrimaryKey(NumberGroupHasTrimesterPk pk) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the criteria 'number_Group = :numberGroup AND name_Trimester = :nameTrimester AND initials_Working_Day = :initialsWorkingDay AND training_Level = :trainingLevel'.
	 */
	public NumberGroupHasTrimester findByPrimaryKey(String numberGroup, String nameTrimester, String initialsWorkingDay, String trainingLevel) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the criteria ''.
	 */
	public NumberGroupHasTrimester[] findAll() throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the criteria 'number_Group = :numberGroup'.
	 */
	public NumberGroupHasTrimester[] findByNumberGroup(String numberGroup) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the criteria 'name_Trimester = :nameTrimester AND initials_Working_Day = :initialsWorkingDay AND training_Level = :trainingLevel'.
	 */
	public NumberGroupHasTrimester[] findByTrimester(String nameTrimester, String initialsWorkingDay, String trainingLevel) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the criteria 'number_Group = :numberGroup'.
	 */
	public NumberGroupHasTrimester[] findWhereNumberGroupEquals(String numberGroup) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the criteria 'name_Trimester = :nameTrimester'.
	 */
	public NumberGroupHasTrimester[] findWhereNameTrimesterEquals(String nameTrimester) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the criteria 'initials_Working_Day = :initialsWorkingDay'.
	 */
	public NumberGroupHasTrimester[] findWhereInitialsWorkingDayEquals(String initialsWorkingDay) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the criteria 'training_Level = :trainingLevel'.
	 */
	public NumberGroupHasTrimester[] findWhereTrainingLevelEquals(String trainingLevel) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the criteria 'number_Group_has_Trimestercol = :numberGroupHasTrimestercol'.
	 */
	public NumberGroupHasTrimester[] findWhereNumberGroupHasTrimestercolEquals(String numberGroupHasTrimestercol) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the specified arbitrary SQL statement
	 */
	public NumberGroupHasTrimester[] findByDynamicSelect(String sql, Object[] sqlParams) throws NumberGroupHasTrimesterDaoException;

	/** 
	 * Returns all rows from the number_group_has_trimester table that match the specified arbitrary SQL statement
	 */
	public NumberGroupHasTrimester[] findByDynamicWhere(String sql, Object[] sqlParams) throws NumberGroupHasTrimesterDaoException;

}
