/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.tidsplan.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the email_server table.
 */
public class EmailServerPk implements Serializable
{
	protected String mail;

	/** 
	 * Sets the value of mail
	 */
	public void setMail(String mail)
	{
		this.mail = mail;
	}

	/** 
	 * Gets the value of mail
	 */
	public String getMail()
	{
		return mail;
	}

	/**
	 * Method 'EmailServerPk'
	 * 
	 */
	public EmailServerPk()
	{
	}

	/**
	 * Method 'EmailServerPk'
	 * 
	 * @param mail
	 */
	public EmailServerPk(final String mail)
	{
		this.mail = mail;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EmailServerPk)) {
			return false;
		}
		
		final EmailServerPk _cast = (EmailServerPk) _other;
		if (mail == null ? _cast.mail != mail : !mail.equals( _cast.mail )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (mail != null) {
			_hashCode = 29 * _hashCode + mail.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.tidsplan.dto.EmailServerPk: " );
		ret.append( "mail=" + mail );
		return ret.toString();
	}

}
