/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.tidsplan.dto;

import co.edu.sena.tidsplan.dao.*;
import co.edu.sena.tidsplan.factory.*;
import co.edu.sena.tidsplan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class GroupHasTrimester implements Serializable
{
	/** 
	 * This attribute maps to the column number_group in the group_has_trimester table.
	 */
	protected String numberGroup;

	/** 
	 * This attribute maps to the column name_trimester in the group_has_trimester table.
	 */
	protected String nameTrimester;

	/** 
	 * This attribute maps to the column workingday_initials in the group_has_trimester table.
	 */
	protected String workingdayInitials;

	/** 
	 * This attribute maps to the column level_formation in the group_has_trimester table.
	 */
	protected String levelFormation;

	/**
	 * Method 'GroupHasTrimester'
	 * 
	 */
	public GroupHasTrimester()
	{
	}

	/**
	 * Method 'getNumberGroup'
	 * 
	 * @return String
	 */
	public String getNumberGroup()
	{
		return numberGroup;
	}

	/**
	 * Method 'setNumberGroup'
	 * 
	 * @param numberGroup
	 */
	public void setNumberGroup(String numberGroup)
	{
		this.numberGroup = numberGroup;
	}

	/**
	 * Method 'getNameTrimester'
	 * 
	 * @return String
	 */
	public String getNameTrimester()
	{
		return nameTrimester;
	}

	/**
	 * Method 'setNameTrimester'
	 * 
	 * @param nameTrimester
	 */
	public void setNameTrimester(String nameTrimester)
	{
		this.nameTrimester = nameTrimester;
	}

	/**
	 * Method 'getWorkingdayInitials'
	 * 
	 * @return String
	 */
	public String getWorkingdayInitials()
	{
		return workingdayInitials;
	}

	/**
	 * Method 'setWorkingdayInitials'
	 * 
	 * @param workingdayInitials
	 */
	public void setWorkingdayInitials(String workingdayInitials)
	{
		this.workingdayInitials = workingdayInitials;
	}

	/**
	 * Method 'getLevelFormation'
	 * 
	 * @return String
	 */
	public String getLevelFormation()
	{
		return levelFormation;
	}

	/**
	 * Method 'setLevelFormation'
	 * 
	 * @param levelFormation
	 */
	public void setLevelFormation(String levelFormation)
	{
		this.levelFormation = levelFormation;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GroupHasTrimester)) {
			return false;
		}
		
		final GroupHasTrimester _cast = (GroupHasTrimester) _other;
		if (numberGroup == null ? _cast.numberGroup != numberGroup : !numberGroup.equals( _cast.numberGroup )) {
			return false;
		}
		
		if (nameTrimester == null ? _cast.nameTrimester != nameTrimester : !nameTrimester.equals( _cast.nameTrimester )) {
			return false;
		}
		
		if (workingdayInitials == null ? _cast.workingdayInitials != workingdayInitials : !workingdayInitials.equals( _cast.workingdayInitials )) {
			return false;
		}
		
		if (levelFormation == null ? _cast.levelFormation != levelFormation : !levelFormation.equals( _cast.levelFormation )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (numberGroup != null) {
			_hashCode = 29 * _hashCode + numberGroup.hashCode();
		}
		
		if (nameTrimester != null) {
			_hashCode = 29 * _hashCode + nameTrimester.hashCode();
		}
		
		if (workingdayInitials != null) {
			_hashCode = 29 * _hashCode + workingdayInitials.hashCode();
		}
		
		if (levelFormation != null) {
			_hashCode = 29 * _hashCode + levelFormation.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return GroupHasTrimesterPk
	 */
	public GroupHasTrimesterPk createPk()
	{
		return new GroupHasTrimesterPk(numberGroup, nameTrimester, workingdayInitials, levelFormation);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.tidsplan.dto.GroupHasTrimester: " );
		ret.append( "numberGroup=" + numberGroup );
		ret.append( ", nameTrimester=" + nameTrimester );
		ret.append( ", workingdayInitials=" + workingdayInitials );
		ret.append( ", levelFormation=" + levelFormation );
		return ret.toString();
	}

}
