/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the actuality_trimester table.
 */
public class ActualityTrimesterPk implements Serializable
{
	protected String actualityTrimester;

	/** 
	 * Sets the value of actualityTrimester
	 */
	public void setActualityTrimester(String actualityTrimester)
	{
		this.actualityTrimester = actualityTrimester;
	}

	/** 
	 * Gets the value of actualityTrimester
	 */
	public String getActualityTrimester()
	{
		return actualityTrimester;
	}

	/**
	 * Method 'ActualityTrimesterPk'
	 * 
	 */
	public ActualityTrimesterPk()
	{
	}

	/**
	 * Method 'ActualityTrimesterPk'
	 * 
	 * @param actualityTrimester
	 */
	public ActualityTrimesterPk(final String actualityTrimester)
	{
		this.actualityTrimester = actualityTrimester;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ActualityTrimesterPk)) {
			return false;
		}
		
		final ActualityTrimesterPk _cast = (ActualityTrimesterPk) _other;
		if (actualityTrimester == null ? _cast.actualityTrimester != actualityTrimester : !actualityTrimester.equals( _cast.actualityTrimester )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (actualityTrimester != null) {
			_hashCode = 29 * _hashCode + actualityTrimester.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.controler.dao.dto.ActualityTrimesterPk: " );
		ret.append( "actualityTrimester=" + actualityTrimester );
		return ret.toString();
	}

}
