/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.dao.dto;

import co.edu.sena.controler.dao.dao.*;
import co.edu.sena.controler.dao.factory.*;
import co.edu.sena.controler.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Availability implements Serializable
{
	/** 
	 * This attribute maps to the column hour_start in the availability table.
	 */
	protected Date hourStart;

	/** 
	 * This attribute maps to the column hour_end in the availability table.
	 */
	protected Date hourEnd;

	/** 
	 * This attribute maps to the column document_type in the availability table.
	 */
	protected String documentType;

	/** 
	 * This attribute maps to the column identification_card in the availability table.
	 */
	protected String identificationCard;

	/** 
	 * This attribute maps to the column name_day in the availability table.
	 */
	protected String nameDay;

	/** 
	 * This attribute maps to the column working_day_initials in the availability table.
	 */
	protected String workingDayInitials;

	/**
	 * Method 'Availability'
	 * 
	 */
	public Availability()
	{
	}

	/**
	 * Method 'getHourStart'
	 * 
	 * @return Date
	 */
	public Date getHourStart()
	{
		return hourStart;
	}

	/**
	 * Method 'setHourStart'
	 * 
	 * @param hourStart
	 */
	public void setHourStart(Date hourStart)
	{
		this.hourStart = hourStart;
	}

	/**
	 * Method 'getHourEnd'
	 * 
	 * @return Date
	 */
	public Date getHourEnd()
	{
		return hourEnd;
	}

	/**
	 * Method 'setHourEnd'
	 * 
	 * @param hourEnd
	 */
	public void setHourEnd(Date hourEnd)
	{
		this.hourEnd = hourEnd;
	}

	/**
	 * Method 'getDocumentType'
	 * 
	 * @return String
	 */
	public String getDocumentType()
	{
		return documentType;
	}

	/**
	 * Method 'setDocumentType'
	 * 
	 * @param documentType
	 */
	public void setDocumentType(String documentType)
	{
		this.documentType = documentType;
	}

	/**
	 * Method 'getIdentificationCard'
	 * 
	 * @return String
	 */
	public String getIdentificationCard()
	{
		return identificationCard;
	}

	/**
	 * Method 'setIdentificationCard'
	 * 
	 * @param identificationCard
	 */
	public void setIdentificationCard(String identificationCard)
	{
		this.identificationCard = identificationCard;
	}

	/**
	 * Method 'getNameDay'
	 * 
	 * @return String
	 */
	public String getNameDay()
	{
		return nameDay;
	}

	/**
	 * Method 'setNameDay'
	 * 
	 * @param nameDay
	 */
	public void setNameDay(String nameDay)
	{
		this.nameDay = nameDay;
	}

	/**
	 * Method 'getWorkingDayInitials'
	 * 
	 * @return String
	 */
	public String getWorkingDayInitials()
	{
		return workingDayInitials;
	}

	/**
	 * Method 'setWorkingDayInitials'
	 * 
	 * @param workingDayInitials
	 */
	public void setWorkingDayInitials(String workingDayInitials)
	{
		this.workingDayInitials = workingDayInitials;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Availability)) {
			return false;
		}
		
		final Availability _cast = (Availability) _other;
		if (hourStart == null ? _cast.hourStart != hourStart : !hourStart.equals( _cast.hourStart )) {
			return false;
		}
		
		if (hourEnd == null ? _cast.hourEnd != hourEnd : !hourEnd.equals( _cast.hourEnd )) {
			return false;
		}
		
		if (documentType == null ? _cast.documentType != documentType : !documentType.equals( _cast.documentType )) {
			return false;
		}
		
		if (identificationCard == null ? _cast.identificationCard != identificationCard : !identificationCard.equals( _cast.identificationCard )) {
			return false;
		}
		
		if (nameDay == null ? _cast.nameDay != nameDay : !nameDay.equals( _cast.nameDay )) {
			return false;
		}
		
		if (workingDayInitials == null ? _cast.workingDayInitials != workingDayInitials : !workingDayInitials.equals( _cast.workingDayInitials )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (hourStart != null) {
			_hashCode = 29 * _hashCode + hourStart.hashCode();
		}
		
		if (hourEnd != null) {
			_hashCode = 29 * _hashCode + hourEnd.hashCode();
		}
		
		if (documentType != null) {
			_hashCode = 29 * _hashCode + documentType.hashCode();
		}
		
		if (identificationCard != null) {
			_hashCode = 29 * _hashCode + identificationCard.hashCode();
		}
		
		if (nameDay != null) {
			_hashCode = 29 * _hashCode + nameDay.hashCode();
		}
		
		if (workingDayInitials != null) {
			_hashCode = 29 * _hashCode + workingDayInitials.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return AvailabilityPk
	 */
	public AvailabilityPk createPk()
	{
		return new AvailabilityPk(hourStart, documentType, identificationCard, nameDay, workingDayInitials);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.controler.dao.dto.Availability: " );
		ret.append( "hourStart=" + hourStart );
		ret.append( ", hourEnd=" + hourEnd );
		ret.append( ", documentType=" + documentType );
		ret.append( ", identificationCard=" + identificationCard );
		ret.append( ", nameDay=" + nameDay );
		ret.append( ", workingDayInitials=" + workingDayInitials );
		return ret.toString();
	}

}
