/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.dao.dto;

import co.edu.sena.controler.dao.dao.*;
import co.edu.sena.controler.dao.factory.*;
import co.edu.sena.controler.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Competence implements Serializable
{
	/** 
	 * This attribute maps to the column competence_code in the competence table.
	 */
	protected String competenceCode;

	/** 
	 * This attribute maps to the column description in the competence table.
	 */
	protected String description;

	/** 
	 * This attribute maps to the column program_code in the competence table.
	 */
	protected String programCode;

	/** 
	 * This attribute maps to the column version in the competence table.
	 */
	protected String version;

	/**
	 * Method 'Competence'
	 * 
	 */
	public Competence()
	{
	}

	/**
	 * Method 'getCompetenceCode'
	 * 
	 * @return String
	 */
	public String getCompetenceCode()
	{
		return competenceCode;
	}

	/**
	 * Method 'setCompetenceCode'
	 * 
	 * @param competenceCode
	 */
	public void setCompetenceCode(String competenceCode)
	{
		this.competenceCode = competenceCode;
	}

	/**
	 * Method 'getDescription'
	 * 
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method 'setDescription'
	 * 
	 * @param description
	 */
	public void setDescription(String description)
	{
		this.description = description;
	}

	/**
	 * Method 'getProgramCode'
	 * 
	 * @return String
	 */
	public String getProgramCode()
	{
		return programCode;
	}

	/**
	 * Method 'setProgramCode'
	 * 
	 * @param programCode
	 */
	public void setProgramCode(String programCode)
	{
		this.programCode = programCode;
	}

	/**
	 * Method 'getVersion'
	 * 
	 * @return String
	 */
	public String getVersion()
	{
		return version;
	}

	/**
	 * Method 'setVersion'
	 * 
	 * @param version
	 */
	public void setVersion(String version)
	{
		this.version = version;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Competence)) {
			return false;
		}
		
		final Competence _cast = (Competence) _other;
		if (competenceCode == null ? _cast.competenceCode != competenceCode : !competenceCode.equals( _cast.competenceCode )) {
			return false;
		}
		
		if (description == null ? _cast.description != description : !description.equals( _cast.description )) {
			return false;
		}
		
		if (programCode == null ? _cast.programCode != programCode : !programCode.equals( _cast.programCode )) {
			return false;
		}
		
		if (version == null ? _cast.version != version : !version.equals( _cast.version )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (competenceCode != null) {
			_hashCode = 29 * _hashCode + competenceCode.hashCode();
		}
		
		if (description != null) {
			_hashCode = 29 * _hashCode + description.hashCode();
		}
		
		if (programCode != null) {
			_hashCode = 29 * _hashCode + programCode.hashCode();
		}
		
		if (version != null) {
			_hashCode = 29 * _hashCode + version.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CompetencePk
	 */
	public CompetencePk createPk()
	{
		return new CompetencePk(competenceCode, programCode, version);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.controler.dao.dto.Competence: " );
		ret.append( "competenceCode=" + competenceCode );
		ret.append( ", description=" + description );
		ret.append( ", programCode=" + programCode );
		ret.append( ", version=" + version );
		return ret.toString();
	}

}
