/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the customer_has_role table.
 */
public class CustomerHasRolePk implements Serializable
{
	protected String personDocumentType;

	protected String identificationCardNumber;

	protected String idRole;

	/** 
	 * Sets the value of personDocumentType
	 */
	public void setPersonDocumentType(String personDocumentType)
	{
		this.personDocumentType = personDocumentType;
	}

	/** 
	 * Gets the value of personDocumentType
	 */
	public String getPersonDocumentType()
	{
		return personDocumentType;
	}

	/** 
	 * Sets the value of identificationCardNumber
	 */
	public void setIdentificationCardNumber(String identificationCardNumber)
	{
		this.identificationCardNumber = identificationCardNumber;
	}

	/** 
	 * Gets the value of identificationCardNumber
	 */
	public String getIdentificationCardNumber()
	{
		return identificationCardNumber;
	}

	/** 
	 * Sets the value of idRole
	 */
	public void setIdRole(String idRole)
	{
		this.idRole = idRole;
	}

	/** 
	 * Gets the value of idRole
	 */
	public String getIdRole()
	{
		return idRole;
	}

	/**
	 * Method 'CustomerHasRolePk'
	 * 
	 */
	public CustomerHasRolePk()
	{
	}

	/**
	 * Method 'CustomerHasRolePk'
	 * 
	 * @param personDocumentType
	 * @param identificationCardNumber
	 * @param idRole
	 */
	public CustomerHasRolePk(final String personDocumentType, final String identificationCardNumber, final String idRole)
	{
		this.personDocumentType = personDocumentType;
		this.identificationCardNumber = identificationCardNumber;
		this.idRole = idRole;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CustomerHasRolePk)) {
			return false;
		}
		
		final CustomerHasRolePk _cast = (CustomerHasRolePk) _other;
		if (personDocumentType == null ? _cast.personDocumentType != personDocumentType : !personDocumentType.equals( _cast.personDocumentType )) {
			return false;
		}
		
		if (identificationCardNumber == null ? _cast.identificationCardNumber != identificationCardNumber : !identificationCardNumber.equals( _cast.identificationCardNumber )) {
			return false;
		}
		
		if (idRole == null ? _cast.idRole != idRole : !idRole.equals( _cast.idRole )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (personDocumentType != null) {
			_hashCode = 29 * _hashCode + personDocumentType.hashCode();
		}
		
		if (identificationCardNumber != null) {
			_hashCode = 29 * _hashCode + identificationCardNumber.hashCode();
		}
		
		if (idRole != null) {
			_hashCode = 29 * _hashCode + idRole.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.controler.dao.dto.CustomerHasRolePk: " );
		ret.append( "personDocumentType=" + personDocumentType );
		ret.append( ", identificationCardNumber=" + identificationCardNumber );
		ret.append( ", idRole=" + idRole );
		return ret.toString();
	}

}
