/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the environment table.
 */
public class EnvironmentPk implements Serializable
{
	protected String numberEnvironment;

	protected String headquartersName;

	/** 
	 * Sets the value of numberEnvironment
	 */
	public void setNumberEnvironment(String numberEnvironment)
	{
		this.numberEnvironment = numberEnvironment;
	}

	/** 
	 * Gets the value of numberEnvironment
	 */
	public String getNumberEnvironment()
	{
		return numberEnvironment;
	}

	/** 
	 * Sets the value of headquartersName
	 */
	public void setHeadquartersName(String headquartersName)
	{
		this.headquartersName = headquartersName;
	}

	/** 
	 * Gets the value of headquartersName
	 */
	public String getHeadquartersName()
	{
		return headquartersName;
	}

	/**
	 * Method 'EnvironmentPk'
	 * 
	 */
	public EnvironmentPk()
	{
	}

	/**
	 * Method 'EnvironmentPk'
	 * 
	 * @param numberEnvironment
	 * @param headquartersName
	 */
	public EnvironmentPk(final String numberEnvironment, final String headquartersName)
	{
		this.numberEnvironment = numberEnvironment;
		this.headquartersName = headquartersName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EnvironmentPk)) {
			return false;
		}
		
		final EnvironmentPk _cast = (EnvironmentPk) _other;
		if (numberEnvironment == null ? _cast.numberEnvironment != numberEnvironment : !numberEnvironment.equals( _cast.numberEnvironment )) {
			return false;
		}
		
		if (headquartersName == null ? _cast.headquartersName != headquartersName : !headquartersName.equals( _cast.headquartersName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (numberEnvironment != null) {
			_hashCode = 29 * _hashCode + numberEnvironment.hashCode();
		}
		
		if (headquartersName != null) {
			_hashCode = 29 * _hashCode + headquartersName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.controler.dao.dto.EnvironmentPk: " );
		ret.append( "numberEnvironment=" + numberEnvironment );
		ret.append( ", headquartersName=" + headquartersName );
		return ret.toString();
	}

}
