/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the identification_card table.
 */
public class IdentificationCardPk implements Serializable
{
	protected String idIdentificationCardNumber;

	/** 
	 * Sets the value of idIdentificationCardNumber
	 */
	public void setIdIdentificationCardNumber(String idIdentificationCardNumber)
	{
		this.idIdentificationCardNumber = idIdentificationCardNumber;
	}

	/** 
	 * Gets the value of idIdentificationCardNumber
	 */
	public String getIdIdentificationCardNumber()
	{
		return idIdentificationCardNumber;
	}

	/**
	 * Method 'IdentificationCardPk'
	 * 
	 */
	public IdentificationCardPk()
	{
	}

	/**
	 * Method 'IdentificationCardPk'
	 * 
	 * @param idIdentificationCardNumber
	 */
	public IdentificationCardPk(final String idIdentificationCardNumber)
	{
		this.idIdentificationCardNumber = idIdentificationCardNumber;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof IdentificationCardPk)) {
			return false;
		}
		
		final IdentificationCardPk _cast = (IdentificationCardPk) _other;
		if (idIdentificationCardNumber == null ? _cast.idIdentificationCardNumber != idIdentificationCardNumber : !idIdentificationCardNumber.equals( _cast.idIdentificationCardNumber )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idIdentificationCardNumber != null) {
			_hashCode = 29 * _hashCode + idIdentificationCardNumber.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.controler.dao.dto.IdentificationCardPk: " );
		ret.append( "idIdentificationCardNumber=" + idIdentificationCardNumber );
		return ret.toString();
	}

}
