/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the log_audit table.
 */
public class LogAuditPk implements Serializable
{
	protected long logAudit;

	/** 
	 * This attribute represents whether the primitive attribute logAudit is null.
	 */
	protected boolean logAuditNull;

	/** 
	 * Sets the value of logAudit
	 */
	public void setLogAudit(long logAudit)
	{
		this.logAudit = logAudit;
	}

	/** 
	 * Gets the value of logAudit
	 */
	public long getLogAudit()
	{
		return logAudit;
	}

	/**
	 * Method 'LogAuditPk'
	 * 
	 */
	public LogAuditPk()
	{
	}

	/**
	 * Method 'LogAuditPk'
	 * 
	 * @param logAudit
	 */
	public LogAuditPk(final long logAudit)
	{
		this.logAudit = logAudit;
	}

	/** 
	 * Sets the value of logAuditNull
	 */
	public void setLogAuditNull(boolean logAuditNull)
	{
		this.logAuditNull = logAuditNull;
	}

	/** 
	 * Gets the value of logAuditNull
	 */
	public boolean isLogAuditNull()
	{
		return logAuditNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof LogAuditPk)) {
			return false;
		}
		
		final LogAuditPk _cast = (LogAuditPk) _other;
		if (logAudit != _cast.logAudit) {
			return false;
		}
		
		if (logAuditNull != _cast.logAuditNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (logAudit ^ (logAudit >>> 32));
		_hashCode = 29 * _hashCode + (logAuditNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.controler.dao.dto.LogAuditPk: " );
		ret.append( "logAudit=" + logAudit );
		return ret.toString();
	}

}
