/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.prueba;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controler.dao.dao.EnvironmentDao;
import co.edu.sena.controler.dao.dto.Environment;
import co.edu.sena.controler.dao.exceptions.EnvironmentDaoException;
import co.edu.sena.controler.dao.factory.EnvironmentDaoFactory;

public class EnvironmentDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByHeadquarters("");
		// findWhereNumberEnvironmentEquals("");
		// findWhereDescriptionEquals("");
		// findWhereStatusEquals(0);
		// findWhereHeadquartersNameEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			EnvironmentDao _dao = getEnvironmentDao();
			Environment _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByHeadquarters'
	 * 
	 * @param headquartersName
	 */
	public static void findByHeadquarters(String headquartersName)
	{
		try {
			EnvironmentDao _dao = getEnvironmentDao();
			Environment _result[] = _dao.findByHeadquarters(headquartersName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNumberEnvironmentEquals'
	 * 
	 * @param numberEnvironment
	 */
	public static void findWhereNumberEnvironmentEquals(String numberEnvironment)
	{
		try {
			EnvironmentDao _dao = getEnvironmentDao();
			Environment _result[] = _dao.findWhereNumberEnvironmentEquals(numberEnvironment);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDescriptionEquals'
	 * 
	 * @param description
	 */
	public static void findWhereDescriptionEquals(String description)
	{
		try {
			EnvironmentDao _dao = getEnvironmentDao();
			Environment _result[] = _dao.findWhereDescriptionEquals(description);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStatusEquals'
	 * 
	 * @param status
	 */
	public static void findWhereStatusEquals(short status)
	{
		try {
			EnvironmentDao _dao = getEnvironmentDao();
			Environment _result[] = _dao.findWhereStatusEquals(status);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereHeadquartersNameEquals'
	 * 
	 * @param headquartersName
	 */
	public static void findWhereHeadquartersNameEquals(String headquartersName)
	{
		try {
			EnvironmentDao _dao = getEnvironmentDao();
			Environment _result[] = _dao.findWhereHeadquartersNameEquals(headquartersName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getEnvironmentDao'
	 * 
	 * @return EnvironmentDao
	 */
	public static EnvironmentDao getEnvironmentDao()
	{
		return EnvironmentDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Environment dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getNumberEnvironment() );
		buf.append( ", " );
		buf.append( dto.getDescription() );
		buf.append( ", " );
		buf.append( dto.getStatus() );
		buf.append( ", " );
		buf.append( dto.getHeadquartersName() );
		System.out.println( buf.toString() );
	}

}
