/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.prueba;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controler.dao.dao.IdentificationCardDao;
import co.edu.sena.controler.dao.dto.IdentificationCard;
import co.edu.sena.controler.dao.exceptions.IdentificationCardDaoException;
import co.edu.sena.controler.dao.factory.IdentificationCardDaoFactory;

public class IdentificationCardDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdIdentificationCardNumberEquals("");
		// findWhereNameEquals("");
		// findWhereStatusEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			IdentificationCardDao _dao = getIdentificationCardDao();
			IdentificationCard _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdIdentificationCardNumberEquals'
	 * 
	 * @param idIdentificationCardNumber
	 */
	public static void findWhereIdIdentificationCardNumberEquals(String idIdentificationCardNumber)
	{
		try {
			IdentificationCardDao _dao = getIdentificationCardDao();
			IdentificationCard _result[] = _dao.findWhereIdIdentificationCardNumberEquals(idIdentificationCardNumber);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 */
	public static void findWhereNameEquals(String name)
	{
		try {
			IdentificationCardDao _dao = getIdentificationCardDao();
			IdentificationCard _result[] = _dao.findWhereNameEquals(name);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStatusEquals'
	 * 
	 * @param status
	 */
	public static void findWhereStatusEquals(short status)
	{
		try {
			IdentificationCardDao _dao = getIdentificationCardDao();
			IdentificationCard _result[] = _dao.findWhereStatusEquals(status);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getIdentificationCardDao'
	 * 
	 * @return IdentificationCardDao
	 */
	public static IdentificationCardDao getIdentificationCardDao()
	{
		return IdentificationCardDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(IdentificationCard dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdIdentificationCardNumber() );
		buf.append( ", " );
		buf.append( dto.getName() );
		buf.append( ", " );
		buf.append( dto.getStatus() );
		System.out.println( buf.toString() );
	}

}
