/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.prueba;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controler.dao.dao.LearningResultHasActivityDao;
import co.edu.sena.controler.dao.dto.LearningResultHasActivity;
import co.edu.sena.controler.dao.exceptions.LearningResultHasActivityDaoException;
import co.edu.sena.controler.dao.factory.LearningResultHasActivityDaoFactory;

public class LearningResultHasActivityDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByActivity("", "", "");
		// findByLearningResult("", "", "", "");
		// findWhereLearningResultCodeEquals("");
		// findWhereCompetenceCodeEquals("");
		// findWhereProgramCodeEquals("");
		// findWhereIdActivityEquals("");
		// findWhereNamePhaseEquals("");
		// findWhereProjectCodeEquals("");
		// findWhereVersionEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByActivity'
	 * 
	 * @param idActivity
	 * @param namePhase
	 * @param projectCode
	 */
	public static void findByActivity(String idActivity, String namePhase, String projectCode)
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findByActivity(idActivity, namePhase, projectCode);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByLearningResult'
	 * 
	 * @param learningResultCode
	 * @param programCode
	 * @param competenceCode
	 * @param version
	 */
	public static void findByLearningResult(String learningResultCode, String programCode, String competenceCode, String version)
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findByLearningResult(learningResultCode, programCode, competenceCode, version);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLearningResultCodeEquals'
	 * 
	 * @param learningResultCode
	 */
	public static void findWhereLearningResultCodeEquals(String learningResultCode)
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findWhereLearningResultCodeEquals(learningResultCode);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCompetenceCodeEquals'
	 * 
	 * @param competenceCode
	 */
	public static void findWhereCompetenceCodeEquals(String competenceCode)
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findWhereCompetenceCodeEquals(competenceCode);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProgramCodeEquals'
	 * 
	 * @param programCode
	 */
	public static void findWhereProgramCodeEquals(String programCode)
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findWhereProgramCodeEquals(programCode);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdActivityEquals'
	 * 
	 * @param idActivity
	 */
	public static void findWhereIdActivityEquals(String idActivity)
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findWhereIdActivityEquals(idActivity);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNamePhaseEquals'
	 * 
	 * @param namePhase
	 */
	public static void findWhereNamePhaseEquals(String namePhase)
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findWhereNamePhaseEquals(namePhase);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProjectCodeEquals'
	 * 
	 * @param projectCode
	 */
	public static void findWhereProjectCodeEquals(String projectCode)
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findWhereProjectCodeEquals(projectCode);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereVersionEquals'
	 * 
	 * @param version
	 */
	public static void findWhereVersionEquals(String version)
	{
		try {
			LearningResultHasActivityDao _dao = getLearningResultHasActivityDao();
			LearningResultHasActivity _result[] = _dao.findWhereVersionEquals(version);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getLearningResultHasActivityDao'
	 * 
	 * @return LearningResultHasActivityDao
	 */
	public static LearningResultHasActivityDao getLearningResultHasActivityDao()
	{
		return LearningResultHasActivityDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(LearningResultHasActivity dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getLearningResultCode() );
		buf.append( ", " );
		buf.append( dto.getCompetenceCode() );
		buf.append( ", " );
		buf.append( dto.getProgramCode() );
		buf.append( ", " );
		buf.append( dto.getIdActivity() );
		buf.append( ", " );
		buf.append( dto.getNamePhase() );
		buf.append( ", " );
		buf.append( dto.getProjectCode() );
		buf.append( ", " );
		buf.append( dto.getVersion() );
		System.out.println( buf.toString() );
	}

}
