/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.prueba;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controler.dao.dao.UserDao;
import co.edu.sena.controler.dao.dto.User;
import co.edu.sena.controler.dao.exceptions.UserDaoException;
import co.edu.sena.controler.dao.factory.UserDaoFactory;

public class UserDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByCustomer("", "");
		// findWhereEmailEquals("");
		// findWherePasswordEquals("");
		// findWhereDocumentTypeEquals("");
		// findWhereIdentificationCardNumberEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCustomer'
	 * 
	 * @param documentType
	 * @param identificationCardNumber
	 */
	public static void findByCustomer(String documentType, String identificationCardNumber)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findByCustomer(documentType, identificationCardNumber);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEmailEquals'
	 * 
	 * @param email
	 */
	public static void findWhereEmailEquals(String email)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereEmailEquals(email);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePasswordEquals'
	 * 
	 * @param password
	 */
	public static void findWherePasswordEquals(String password)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWherePasswordEquals(password);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDocumentTypeEquals'
	 * 
	 * @param documentType
	 */
	public static void findWhereDocumentTypeEquals(String documentType)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereDocumentTypeEquals(documentType);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdentificationCardNumberEquals'
	 * 
	 * @param identificationCardNumber
	 */
	public static void findWhereIdentificationCardNumberEquals(String identificationCardNumber)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereIdentificationCardNumberEquals(identificationCardNumber);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getUserDao'
	 * 
	 * @return UserDao
	 */
	public static UserDao getUserDao()
	{
		return UserDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(User dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getEmail() );
		buf.append( ", " );
		buf.append( dto.getPassword() );
		buf.append( ", " );
		buf.append( dto.getDocumentType() );
		buf.append( ", " );
		buf.append( dto.getIdentificationCardNumber() );
		System.out.println( buf.toString() );
	}

}
