/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.dao.dao;

import co.edu.sena.controler.dao.dto.*;
import co.edu.sena.controler.dao.exceptions.*;

public interface GroupNumberHasTrimesterHasLearningResultDao
{
	/** 
	 * Inserts a new row in the group_number_has_trimester_has_learning_result table.
	 */
	public GroupNumberHasTrimesterHasLearningResultPk insert(GroupNumberHasTrimesterHasLearningResult dto) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Updates a single row in the group_number_has_trimester_has_learning_result table.
	 */
	public void update(GroupNumberHasTrimesterHasLearningResultPk pk, GroupNumberHasTrimesterHasLearningResult dto) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Deletes a single row in the group_number_has_trimester_has_learning_result table.
	 */
	public void delete(GroupNumberHasTrimesterHasLearningResultPk pk) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns the rows from the group_number_has_trimester_has_learning_result table that matches the specified primary-key value.
	 */
	public GroupNumberHasTrimesterHasLearningResult findByPrimaryKey(GroupNumberHasTrimesterHasLearningResultPk pk) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'group_number = :groupNumber AND trimester_name = :trimesterName AND working_day_initials = :workingDayInitials AND level_formation = :levelFormation AND learning_result_code = :learningResultCode AND program_code = :programCode AND competence_code = :competenceCode AND version = :version'.
	 */
	public GroupNumberHasTrimesterHasLearningResult findByPrimaryKey(String groupNumber, String trimesterName, String workingDayInitials, String levelFormation, String learningResultCode, String programCode, String competenceCode, String version) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria ''.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findAll() throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'group_number = :groupNumber AND trimester_name = :trimesterName AND working_day_initials = :workingDayInitials AND level_formation = :levelFormation'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findByGroupNumberHasTrimester(String groupNumber, String trimesterName, String workingDayInitials, String levelFormation) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'learning_result_code = :learningResultCode AND program_code = :programCode AND competence_code = :competenceCode AND version = :version'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findByLearningResult(String learningResultCode, String programCode, String competenceCode, String version) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'group_number = :groupNumber'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findWhereGroupNumberEquals(String groupNumber) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'trimester_name = :trimesterName'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findWhereTrimesterNameEquals(String trimesterName) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'working_day_initials = :workingDayInitials'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findWhereWorkingDayInitialsEquals(String workingDayInitials) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'learning_result_code = :learningResultCode'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findWhereLearningResultCodeEquals(String learningResultCode) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'program_code = :programCode'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findWhereProgramCodeEquals(String programCode) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'competence_code = :competenceCode'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findWhereCompetenceCodeEquals(String competenceCode) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'level_formation = :levelFormation'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findWhereLevelFormationEquals(String levelFormation) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the criteria 'version = :version'.
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findWhereVersionEquals(String version) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the specified arbitrary SQL statement
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findByDynamicSelect(String sql, Object[] sqlParams) throws GroupNumberHasTrimesterHasLearningResultDaoException;

	/** 
	 * Returns all rows from the group_number_has_trimester_has_learning_result table that match the specified arbitrary SQL statement
	 */
	public GroupNumberHasTrimesterHasLearningResult[] findByDynamicWhere(String sql, Object[] sqlParams) throws GroupNumberHasTrimesterHasLearningResultDaoException;

}
