/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.tidsplan.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.tidsplan.dao.TrimesterDao;
import co.edu.sena.tidsplan.dto.Trimester;
import co.edu.sena.tidsplan.exceptions.TrimesterDaoException;
import co.edu.sena.tidsplan.factory.TrimesterDaoFactory;

public class TrimesterDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		 findAll();
		// findByFormationLevel("");
		// findByWorkingDay("");
		// findWhereNameTrimesterEquals("");
		// findWhereWorkingdayInitialsEquals("");
		// findWhereLevelFormationEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			TrimesterDao _dao = getTrimesterDao();
			Trimester _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByFormationLevel'
	 * 
	 * @param levelFormation
	 */
	public static void findByFormationLevel(String levelFormation)
	{
		try {
			TrimesterDao _dao = getTrimesterDao();
			Trimester _result[] = _dao.findByFormationLevel(levelFormation);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByWorkingDay'
	 * 
	 * @param workingdayInitials
	 */
	public static void findByWorkingDay(String workingdayInitials)
	{
		try {
			TrimesterDao _dao = getTrimesterDao();
			Trimester _result[] = _dao.findByWorkingDay(workingdayInitials);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNameTrimesterEquals'
	 * 
	 * @param nameTrimester
	 */
	public static void findWhereNameTrimesterEquals(String nameTrimester)
	{
		try {
			TrimesterDao _dao = getTrimesterDao();
			Trimester _result[] = _dao.findWhereNameTrimesterEquals(nameTrimester);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereWorkingdayInitialsEquals'
	 * 
	 * @param workingdayInitials
	 */
	public static void findWhereWorkingdayInitialsEquals(String workingdayInitials)
	{
		try {
			TrimesterDao _dao = getTrimesterDao();
			Trimester _result[] = _dao.findWhereWorkingdayInitialsEquals(workingdayInitials);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLevelFormationEquals'
	 * 
	 * @param levelFormation
	 */
	public static void findWhereLevelFormationEquals(String levelFormation)
	{
		try {
			TrimesterDao _dao = getTrimesterDao();
			Trimester _result[] = _dao.findWhereLevelFormationEquals(levelFormation);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getTrimesterDao'
	 * 
	 * @return TrimesterDao
	 */
	public static TrimesterDao getTrimesterDao()
	{
		return TrimesterDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Trimester dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getNameTrimester() );
		buf.append( ", " );
		buf.append( dto.getWorkingdayInitials() );
		buf.append( ", " );
		buf.append( dto.getLevelFormation() );
		System.out.println( buf.toString() );
	}

}
