/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.model.dao.dao.TrainingLevelDao;
import co.edu.sena.model.dao.dto.TrainingLevel;
import co.edu.sena.model.dao.exceptions.TrainingLevelDaoException;
import co.edu.sena.model.dao.factory.TrainingLevelDaoFactory;

public class TrainingLevelDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		 findAll();
		// findWhereTrainingLevelEquals("");
		// findWhereStateEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			TrainingLevelDao _dao = getTrainingLevelDao();
			TrainingLevel _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTrainingLevelEquals'
	 * 
	 * @param trainingLevel
	 */
	public static void findWhereTrainingLevelEquals(String trainingLevel)
	{
		try {
			TrainingLevelDao _dao = getTrainingLevelDao();
			TrainingLevel _result[] = _dao.findWhereTrainingLevelEquals(trainingLevel);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStateEquals'
	 * 
	 * @param state
	 */
	public static void findWhereStateEquals(short state)
	{
		try {
			TrainingLevelDao _dao = getTrainingLevelDao();
			TrainingLevel _result[] = _dao.findWhereStateEquals(state);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getTrainingLevelDao'
	 * 
	 * @return TrainingLevelDao
	 */
	public static TrainingLevelDao getTrainingLevelDao()
	{
		return TrainingLevelDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(TrainingLevel dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getTrainingLevel() );
		buf.append( ", " );
		buf.append( dto.getState() );
		System.out.println( buf.toString() );
	}

}
