/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.model.dao.dao.VersionDao;
import co.edu.sena.model.dao.dto.Version;
import co.edu.sena.model.dao.exceptions.VersionDaoException;
import co.edu.sena.model.dao.factory.VersionDaoFactory;

public class VersionDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		 findAll();
		// findByCurrentQuarter("");
		// findWhereIdVersionEquals(0);
		// findWhereActiveEquals(0);
		// findWhereIdCurrentQuarterEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			VersionDao _dao = getVersionDao();
			Version _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCurrentQuarter'
	 * 
	 * @param idCurrentQuarter
	 */
	public static void findByCurrentQuarter(String idCurrentQuarter)
	{
		try {
			VersionDao _dao = getVersionDao();
			Version _result[] = _dao.findByCurrentQuarter(idCurrentQuarter);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdVersionEquals'
	 * 
	 * @param idVersion
	 */
	public static void findWhereIdVersionEquals(int idVersion)
	{
		try {
			VersionDao _dao = getVersionDao();
			Version _result[] = _dao.findWhereIdVersionEquals(idVersion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereActiveEquals'
	 * 
	 * @param active
	 */
	public static void findWhereActiveEquals(short active)
	{
		try {
			VersionDao _dao = getVersionDao();
			Version _result[] = _dao.findWhereActiveEquals(active);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdCurrentQuarterEquals'
	 * 
	 * @param idCurrentQuarter
	 */
	public static void findWhereIdCurrentQuarterEquals(String idCurrentQuarter)
	{
		try {
			VersionDao _dao = getVersionDao();
			Version _result[] = _dao.findWhereIdCurrentQuarterEquals(idCurrentQuarter);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getVersionDao'
	 * 
	 * @return VersionDao
	 */
	public static VersionDao getVersionDao()
	{
		return VersionDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Version dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdVersion() );
		buf.append( ", " );
		buf.append( dto.getActive() );
		buf.append( ", " );
		buf.append( dto.getIdCurrentQuarter() );
		System.out.println( buf.toString() );
	}

}
