/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.dao;

import co.edu.sena.dto.*;
import co.edu.sena.exceptions.*;

public interface VersionDao
{
	/** 
	 * Inserts a new row in the version table.
	 */
	public VersionPk insert(Version dto) throws VersionDaoException;

	/** 
	 * Updates a single row in the version table.
	 */
	public void update(VersionPk pk, Version dto) throws VersionDaoException;

	/** 
	 * Deletes a single row in the version table.
	 */
	public void delete(VersionPk pk) throws VersionDaoException;

	/** 
	 * Returns the rows from the version table that matches the specified primary-key value.
	 */
	public Version findByPrimaryKey(VersionPk pk) throws VersionDaoException;

	/** 
	 * Returns all rows from the version table that match the criteria 'idCurrent_Quarter = :idcurrentQuarter AND idVersion = :idVersion'.
	 */
	public Version findByPrimaryKey(String idcurrentQuarter, int idVersion) throws VersionDaoException;

	/** 
	 * Returns all rows from the version table that match the criteria ''.
	 */
	public Version[] findAll() throws VersionDaoException;

	/** 
	 * Returns all rows from the version table that match the criteria 'idCurrent_Quarter = :idcurrentQuarter'.
	 */
	public Version[] findByCurrentQuarter(String idcurrentQuarter) throws VersionDaoException;

	/** 
	 * Returns all rows from the version table that match the criteria 'idVersion = :idVersion'.
	 */
	public Version[] findWhereIdVersionEquals(int idVersion) throws VersionDaoException;

	/** 
	 * Returns all rows from the version table that match the criteria 'active = :active'.
	 */
	public Version[] findWhereActiveEquals(short active) throws VersionDaoException;

	/** 
	 * Returns all rows from the version table that match the criteria 'idCurrent_Quarter = :idcurrentQuarter'.
	 */
	public Version[] findWhereIdcurrentQuarterEquals(String idcurrentQuarter) throws VersionDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the version table that match the specified arbitrary SQL statement
	 */
	public Version[] findByDynamicSelect(String sql, Object[] sqlParams) throws VersionDaoException;

	/** 
	 * Returns all rows from the version table that match the specified arbitrary SQL statement
	 */
	public Version[] findByDynamicWhere(String sql, Object[] sqlParams) throws VersionDaoException;

}
