/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controler.dao.jdbc;

import co.edu.sena.controler.dao.dao.*;
import co.edu.sena.controler.dao.factory.*;
import co.edu.sena.controler.dao.dto.*;
import co.edu.sena.controler.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class LevelFormationDaoImpl extends AbstractDAO implements LevelFormationDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT level_formation, status FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( level_formation, status ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET level_formation = ?, status = ? WHERE level_formation = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE level_formation = ?";

	/** 
	 * Index of column level_formation
	 */
	protected static final int COLUMN_LEVEL_FORMATION = 1;

	/** 
	 * Index of column status
	 */
	protected static final int COLUMN_STATUS = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column level_formation
	 */
	protected static final int PK_COLUMN_LEVEL_FORMATION = 1;

	/** 
	 * Inserts a new row in the level_formation table.
	 */
	public LevelFormationPk insert(LevelFormation dto) throws LevelFormationDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getLevelFormation() );
			stmt.setShort( index++, dto.getStatus() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LevelFormationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the level_formation table.
	 */
	public void update(LevelFormationPk pk, LevelFormation dto) throws LevelFormationDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setString( index++, dto.getLevelFormation() );
			stmt.setShort( index++, dto.getStatus() );
			stmt.setString( 3, pk.getLevelFormation() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LevelFormationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the level_formation table.
	 */
	public void delete(LevelFormationPk pk) throws LevelFormationDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getLevelFormation() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LevelFormationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the level_formation table that matches the specified primary-key value.
	 */
	public LevelFormation findByPrimaryKey(LevelFormationPk pk) throws LevelFormationDaoException
	{
		return findByPrimaryKey( pk.getLevelFormation() );
	}

	/** 
	 * Returns all rows from the level_formation table that match the criteria 'level_formation = :levelFormation'.
	 */
	public LevelFormation findByPrimaryKey(String levelFormation) throws LevelFormationDaoException
	{
		LevelFormation ret[] = findByDynamicSelect( SQL_SELECT + " WHERE level_formation = ?", new Object[] { levelFormation } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the level_formation table that match the criteria ''.
	 */
	public LevelFormation[] findAll() throws LevelFormationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY level_formation", null );
	}

	/** 
	 * Returns all rows from the level_formation table that match the criteria 'level_formation = :levelFormation'.
	 */
	public LevelFormation[] findWhereLevelFormationEquals(String levelFormation) throws LevelFormationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE level_formation = ? ORDER BY level_formation", new Object[] { levelFormation } );
	}

	/** 
	 * Returns all rows from the level_formation table that match the criteria 'status = :status'.
	 */
	public LevelFormation[] findWhereStatusEquals(short status) throws LevelFormationDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE status = ? ORDER BY status", new Object[] {  new Short(status) } );
	}

	/**
	 * Method 'LevelFormationDaoImpl'
	 * 
	 */
	public LevelFormationDaoImpl()
	{
	}

	/**
	 * Method 'LevelFormationDaoImpl'
	 * 
	 * @param userConn
	 */
	public LevelFormationDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "joycd.level_formation";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected LevelFormation fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			LevelFormation dto = new LevelFormation();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected LevelFormation[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			LevelFormation dto = new LevelFormation();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		LevelFormation ret[] = new LevelFormation[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(LevelFormation dto, ResultSet rs) throws SQLException
	{
		dto.setLevelFormation( rs.getString( COLUMN_LEVEL_FORMATION ) );
		dto.setStatus( rs.getShort( COLUMN_STATUS ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(LevelFormation dto)
	{
	}

	/** 
	 * Returns all rows from the level_formation table that match the specified arbitrary SQL statement
	 */
	public LevelFormation[] findByDynamicSelect(String sql, Object[] sqlParams) throws LevelFormationDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LevelFormationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the level_formation table that match the specified arbitrary SQL statement
	 */
	public LevelFormation[] findByDynamicWhere(String sql, Object[] sqlParams) throws LevelFormationDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new LevelFormationDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
