/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the learning_outcome table.
 */
public class LearningOutcomePk implements Serializable
{
	protected String lOutcomeCode;

	protected String competitionCode;

	protected String programCode;

	protected String version;

	/** 
	 * Sets the value of lOutcomeCode
	 */
	public void setLOutcomeCode(String lOutcomeCode)
	{
		this.lOutcomeCode = lOutcomeCode;
	}

	/** 
	 * Gets the value of lOutcomeCode
	 */
	public String getLOutcomeCode()
	{
		return lOutcomeCode;
	}

	/** 
	 * Sets the value of competitionCode
	 */
	public void setCompetitionCode(String competitionCode)
	{
		this.competitionCode = competitionCode;
	}

	/** 
	 * Gets the value of competitionCode
	 */
	public String getCompetitionCode()
	{
		return competitionCode;
	}

	/** 
	 * Sets the value of programCode
	 */
	public void setProgramCode(String programCode)
	{
		this.programCode = programCode;
	}

	/** 
	 * Gets the value of programCode
	 */
	public String getProgramCode()
	{
		return programCode;
	}

	/** 
	 * Sets the value of version
	 */
	public void setVersion(String version)
	{
		this.version = version;
	}

	/** 
	 * Gets the value of version
	 */
	public String getVersion()
	{
		return version;
	}

	/**
	 * Method 'LearningOutcomePk'
	 * 
	 */
	public LearningOutcomePk()
	{
	}

	/**
	 * Method 'LearningOutcomePk'
	 * 
	 * @param lOutcomeCode
	 * @param competitionCode
	 * @param programCode
	 * @param version
	 */
	public LearningOutcomePk(final String lOutcomeCode, final String competitionCode, final String programCode, final String version)
	{
		this.lOutcomeCode = lOutcomeCode;
		this.competitionCode = competitionCode;
		this.programCode = programCode;
		this.version = version;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof LearningOutcomePk)) {
			return false;
		}
		
		final LearningOutcomePk _cast = (LearningOutcomePk) _other;
		if (lOutcomeCode == null ? _cast.lOutcomeCode != lOutcomeCode : !lOutcomeCode.equals( _cast.lOutcomeCode )) {
			return false;
		}
		
		if (competitionCode == null ? _cast.competitionCode != competitionCode : !competitionCode.equals( _cast.competitionCode )) {
			return false;
		}
		
		if (programCode == null ? _cast.programCode != programCode : !programCode.equals( _cast.programCode )) {
			return false;
		}
		
		if (version == null ? _cast.version != version : !version.equals( _cast.version )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (lOutcomeCode != null) {
			_hashCode = 29 * _hashCode + lOutcomeCode.hashCode();
		}
		
		if (competitionCode != null) {
			_hashCode = 29 * _hashCode + competitionCode.hashCode();
		}
		
		if (programCode != null) {
			_hashCode = 29 * _hashCode + programCode.hashCode();
		}
		
		if (version != null) {
			_hashCode = 29 * _hashCode + version.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.LearningOutcomePk: " );
		ret.append( "lOutcomeCode=" + lOutcomeCode );
		ret.append( ", competitionCode=" + competitionCode );
		ret.append( ", programCode=" + programCode );
		ret.append( ", version=" + version );
		return ret.toString();
	}

}
