/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the number_group table.
 */
public class NumberGroupPk implements Serializable
{
	protected String numberGroup;

	protected String version;

	/** 
	 * Sets the value of numberGroup
	 */
	public void setNumberGroup(String numberGroup)
	{
		this.numberGroup = numberGroup;
	}

	/** 
	 * Gets the value of numberGroup
	 */
	public String getNumberGroup()
	{
		return numberGroup;
	}

	/** 
	 * Sets the value of version
	 */
	public void setVersion(String version)
	{
		this.version = version;
	}

	/** 
	 * Gets the value of version
	 */
	public String getVersion()
	{
		return version;
	}

	/**
	 * Method 'NumberGroupPk'
	 * 
	 */
	public NumberGroupPk()
	{
	}

	/**
	 * Method 'NumberGroupPk'
	 * 
	 * @param numberGroup
	 * @param version
	 */
	public NumberGroupPk(final String numberGroup, final String version)
	{
		this.numberGroup = numberGroup;
		this.version = version;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof NumberGroupPk)) {
			return false;
		}
		
		final NumberGroupPk _cast = (NumberGroupPk) _other;
		if (numberGroup == null ? _cast.numberGroup != numberGroup : !numberGroup.equals( _cast.numberGroup )) {
			return false;
		}
		
		if (version == null ? _cast.version != version : !version.equals( _cast.version )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (numberGroup != null) {
			_hashCode = 29 * _hashCode + numberGroup.hashCode();
		}
		
		if (version != null) {
			_hashCode = 29 * _hashCode + version.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.NumberGroupPk: " );
		ret.append( "numberGroup=" + numberGroup );
		ret.append( ", version=" + version );
		return ret.toString();
	}

}
