/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the role_has_client table.
 */
public class RoleHasClientPk implements Serializable
{
	protected String idDocument;

	protected String documentNumber;

	protected String idRole;

	/** 
	 * Sets the value of idDocument
	 */
	public void setIdDocument(String idDocument)
	{
		this.idDocument = idDocument;
	}

	/** 
	 * Gets the value of idDocument
	 */
	public String getIdDocument()
	{
		return idDocument;
	}

	/** 
	 * Sets the value of documentNumber
	 */
	public void setDocumentNumber(String documentNumber)
	{
		this.documentNumber = documentNumber;
	}

	/** 
	 * Gets the value of documentNumber
	 */
	public String getDocumentNumber()
	{
		return documentNumber;
	}

	/** 
	 * Sets the value of idRole
	 */
	public void setIdRole(String idRole)
	{
		this.idRole = idRole;
	}

	/** 
	 * Gets the value of idRole
	 */
	public String getIdRole()
	{
		return idRole;
	}

	/**
	 * Method 'RoleHasClientPk'
	 * 
	 */
	public RoleHasClientPk()
	{
	}

	/**
	 * Method 'RoleHasClientPk'
	 * 
	 * @param idDocument
	 * @param documentNumber
	 * @param idRole
	 */
	public RoleHasClientPk(final String idDocument, final String documentNumber, final String idRole)
	{
		this.idDocument = idDocument;
		this.documentNumber = documentNumber;
		this.idRole = idRole;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof RoleHasClientPk)) {
			return false;
		}
		
		final RoleHasClientPk _cast = (RoleHasClientPk) _other;
		if (idDocument == null ? _cast.idDocument != idDocument : !idDocument.equals( _cast.idDocument )) {
			return false;
		}
		
		if (documentNumber == null ? _cast.documentNumber != documentNumber : !documentNumber.equals( _cast.documentNumber )) {
			return false;
		}
		
		if (idRole == null ? _cast.idRole != idRole : !idRole.equals( _cast.idRole )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idDocument != null) {
			_hashCode = 29 * _hashCode + idDocument.hashCode();
		}
		
		if (documentNumber != null) {
			_hashCode = 29 * _hashCode + documentNumber.hashCode();
		}
		
		if (idRole != null) {
			_hashCode = 29 * _hashCode + idRole.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.RoleHasClientPk: " );
		ret.append( "idDocument=" + idDocument );
		ret.append( ", documentNumber=" + documentNumber );
		ret.append( ", idRole=" + idRole );
		return ret.toString();
	}

}
