/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.model.dao.dao.*;
import co.edu.sena.model.dao.factory.*;
import co.edu.sena.model.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Schedule implements Serializable
{
	/** 
	 * This attribute maps to the column start_Time in the schedule table.
	 */
	protected String startTime;

	/** 
	 * This attribute maps to the column end_Time in the schedule table.
	 */
	protected String endTime;

	/** 
	 * This attribute maps to the column name_Trimester in the schedule table.
	 */
	protected String nameTrimester;

	/** 
	 * This attribute maps to the column number_Group in the schedule table.
	 */
	protected String numberGroup;

	/** 
	 * This attribute maps to the column initials_Working_Day in the schedule table.
	 */
	protected String initialsWorkingDay;

	/** 
	 * This attribute maps to the column document_Number in the schedule table.
	 */
	protected String documentNumber;

	/** 
	 * This attribute maps to the column id_Document in the schedule table.
	 */
	protected String idDocument;

	/** 
	 * This attribute maps to the column name_Day in the schedule table.
	 */
	protected String nameDay;

	/** 
	 * This attribute maps to the column name_Modality in the schedule table.
	 */
	protected String nameModality;

	/** 
	 * This attribute maps to the column number_Environment in the schedule table.
	 */
	protected String numberEnvironment;

	/** 
	 * This attribute maps to the column name_Headquarters in the schedule table.
	 */
	protected String nameHeadquarters;

	/** 
	 * This attribute maps to the column id_Version in the schedule table.
	 */
	protected int idVersion;

	/** 
	 * This attribute maps to the column id_Current_Quarter in the schedule table.
	 */
	protected String idCurrentQuarter;

	/**
	 * Method 'Schedule'
	 * 
	 */
	public Schedule()
	{
	}

	/**
	 * Method 'getStartTime'
	 * 
	 * @return String
	 */
	public String getStartTime()
	{
		return startTime;
	}

	/**
	 * Method 'setStartTime'
	 * 
	 * @param startTime
	 */
	public void setStartTime(String startTime)
	{
		this.startTime = startTime;
	}

	/**
	 * Method 'getEndTime'
	 * 
	 * @return String
	 */
	public String getEndTime()
	{
		return endTime;
	}

	/**
	 * Method 'setEndTime'
	 * 
	 * @param endTime
	 */
	public void setEndTime(String endTime)
	{
		this.endTime = endTime;
	}

	/**
	 * Method 'getNameTrimester'
	 * 
	 * @return String
	 */
	public String getNameTrimester()
	{
		return nameTrimester;
	}

	/**
	 * Method 'setNameTrimester'
	 * 
	 * @param nameTrimester
	 */
	public void setNameTrimester(String nameTrimester)
	{
		this.nameTrimester = nameTrimester;
	}

	/**
	 * Method 'getNumberGroup'
	 * 
	 * @return String
	 */
	public String getNumberGroup()
	{
		return numberGroup;
	}

	/**
	 * Method 'setNumberGroup'
	 * 
	 * @param numberGroup
	 */
	public void setNumberGroup(String numberGroup)
	{
		this.numberGroup = numberGroup;
	}

	/**
	 * Method 'getInitialsWorkingDay'
	 * 
	 * @return String
	 */
	public String getInitialsWorkingDay()
	{
		return initialsWorkingDay;
	}

	/**
	 * Method 'setInitialsWorkingDay'
	 * 
	 * @param initialsWorkingDay
	 */
	public void setInitialsWorkingDay(String initialsWorkingDay)
	{
		this.initialsWorkingDay = initialsWorkingDay;
	}

	/**
	 * Method 'getDocumentNumber'
	 * 
	 * @return String
	 */
	public String getDocumentNumber()
	{
		return documentNumber;
	}

	/**
	 * Method 'setDocumentNumber'
	 * 
	 * @param documentNumber
	 */
	public void setDocumentNumber(String documentNumber)
	{
		this.documentNumber = documentNumber;
	}

	/**
	 * Method 'getIdDocument'
	 * 
	 * @return String
	 */
	public String getIdDocument()
	{
		return idDocument;
	}

	/**
	 * Method 'setIdDocument'
	 * 
	 * @param idDocument
	 */
	public void setIdDocument(String idDocument)
	{
		this.idDocument = idDocument;
	}

	/**
	 * Method 'getNameDay'
	 * 
	 * @return String
	 */
	public String getNameDay()
	{
		return nameDay;
	}

	/**
	 * Method 'setNameDay'
	 * 
	 * @param nameDay
	 */
	public void setNameDay(String nameDay)
	{
		this.nameDay = nameDay;
	}

	/**
	 * Method 'getNameModality'
	 * 
	 * @return String
	 */
	public String getNameModality()
	{
		return nameModality;
	}

	/**
	 * Method 'setNameModality'
	 * 
	 * @param nameModality
	 */
	public void setNameModality(String nameModality)
	{
		this.nameModality = nameModality;
	}

	/**
	 * Method 'getNumberEnvironment'
	 * 
	 * @return String
	 */
	public String getNumberEnvironment()
	{
		return numberEnvironment;
	}

	/**
	 * Method 'setNumberEnvironment'
	 * 
	 * @param numberEnvironment
	 */
	public void setNumberEnvironment(String numberEnvironment)
	{
		this.numberEnvironment = numberEnvironment;
	}

	/**
	 * Method 'getNameHeadquarters'
	 * 
	 * @return String
	 */
	public String getNameHeadquarters()
	{
		return nameHeadquarters;
	}

	/**
	 * Method 'setNameHeadquarters'
	 * 
	 * @param nameHeadquarters
	 */
	public void setNameHeadquarters(String nameHeadquarters)
	{
		this.nameHeadquarters = nameHeadquarters;
	}

	/**
	 * Method 'getIdVersion'
	 * 
	 * @return int
	 */
	public int getIdVersion()
	{
		return idVersion;
	}

	/**
	 * Method 'setIdVersion'
	 * 
	 * @param idVersion
	 */
	public void setIdVersion(int idVersion)
	{
		this.idVersion = idVersion;
	}

	/**
	 * Method 'getIdCurrentQuarter'
	 * 
	 * @return String
	 */
	public String getIdCurrentQuarter()
	{
		return idCurrentQuarter;
	}

	/**
	 * Method 'setIdCurrentQuarter'
	 * 
	 * @param idCurrentQuarter
	 */
	public void setIdCurrentQuarter(String idCurrentQuarter)
	{
		this.idCurrentQuarter = idCurrentQuarter;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Schedule)) {
			return false;
		}
		
		final Schedule _cast = (Schedule) _other;
		if (startTime == null ? _cast.startTime != startTime : !startTime.equals( _cast.startTime )) {
			return false;
		}
		
		if (endTime == null ? _cast.endTime != endTime : !endTime.equals( _cast.endTime )) {
			return false;
		}
		
		if (nameTrimester == null ? _cast.nameTrimester != nameTrimester : !nameTrimester.equals( _cast.nameTrimester )) {
			return false;
		}
		
		if (numberGroup == null ? _cast.numberGroup != numberGroup : !numberGroup.equals( _cast.numberGroup )) {
			return false;
		}
		
		if (initialsWorkingDay == null ? _cast.initialsWorkingDay != initialsWorkingDay : !initialsWorkingDay.equals( _cast.initialsWorkingDay )) {
			return false;
		}
		
		if (documentNumber == null ? _cast.documentNumber != documentNumber : !documentNumber.equals( _cast.documentNumber )) {
			return false;
		}
		
		if (idDocument == null ? _cast.idDocument != idDocument : !idDocument.equals( _cast.idDocument )) {
			return false;
		}
		
		if (nameDay == null ? _cast.nameDay != nameDay : !nameDay.equals( _cast.nameDay )) {
			return false;
		}
		
		if (nameModality == null ? _cast.nameModality != nameModality : !nameModality.equals( _cast.nameModality )) {
			return false;
		}
		
		if (numberEnvironment == null ? _cast.numberEnvironment != numberEnvironment : !numberEnvironment.equals( _cast.numberEnvironment )) {
			return false;
		}
		
		if (nameHeadquarters == null ? _cast.nameHeadquarters != nameHeadquarters : !nameHeadquarters.equals( _cast.nameHeadquarters )) {
			return false;
		}
		
		if (idVersion != _cast.idVersion) {
			return false;
		}
		
		if (idCurrentQuarter == null ? _cast.idCurrentQuarter != idCurrentQuarter : !idCurrentQuarter.equals( _cast.idCurrentQuarter )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (startTime != null) {
			_hashCode = 29 * _hashCode + startTime.hashCode();
		}
		
		if (endTime != null) {
			_hashCode = 29 * _hashCode + endTime.hashCode();
		}
		
		if (nameTrimester != null) {
			_hashCode = 29 * _hashCode + nameTrimester.hashCode();
		}
		
		if (numberGroup != null) {
			_hashCode = 29 * _hashCode + numberGroup.hashCode();
		}
		
		if (initialsWorkingDay != null) {
			_hashCode = 29 * _hashCode + initialsWorkingDay.hashCode();
		}
		
		if (documentNumber != null) {
			_hashCode = 29 * _hashCode + documentNumber.hashCode();
		}
		
		if (idDocument != null) {
			_hashCode = 29 * _hashCode + idDocument.hashCode();
		}
		
		if (nameDay != null) {
			_hashCode = 29 * _hashCode + nameDay.hashCode();
		}
		
		if (nameModality != null) {
			_hashCode = 29 * _hashCode + nameModality.hashCode();
		}
		
		if (numberEnvironment != null) {
			_hashCode = 29 * _hashCode + numberEnvironment.hashCode();
		}
		
		if (nameHeadquarters != null) {
			_hashCode = 29 * _hashCode + nameHeadquarters.hashCode();
		}
		
		_hashCode = 29 * _hashCode + idVersion;
		if (idCurrentQuarter != null) {
			_hashCode = 29 * _hashCode + idCurrentQuarter.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SchedulePk
	 */
	public SchedulePk createPk()
	{
		return new SchedulePk(idDocument, documentNumber, nameModality, numberEnvironment, nameHeadquarters, idVersion, idCurrentQuarter, nameDay, numberGroup, nameTrimester, initialsWorkingDay);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.Schedule: " );
		ret.append( "startTime=" + startTime );
		ret.append( ", endTime=" + endTime );
		ret.append( ", nameTrimester=" + nameTrimester );
		ret.append( ", numberGroup=" + numberGroup );
		ret.append( ", initialsWorkingDay=" + initialsWorkingDay );
		ret.append( ", documentNumber=" + documentNumber );
		ret.append( ", idDocument=" + idDocument );
		ret.append( ", nameDay=" + nameDay );
		ret.append( ", nameModality=" + nameModality );
		ret.append( ", numberEnvironment=" + numberEnvironment );
		ret.append( ", nameHeadquarters=" + nameHeadquarters );
		ret.append( ", idVersion=" + idVersion );
		ret.append( ", idCurrentQuarter=" + idCurrentQuarter );
		return ret.toString();
	}

}
