/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.model.dao.dao.*;
import co.edu.sena.model.dao.factory.*;
import co.edu.sena.model.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Teacher implements Serializable
{
	/** 
	 * This attribute maps to the column id_Document in the teacher table.
	 */
	protected String idDocument;

	/** 
	 * This attribute maps to the column document_Number in the teacher table.
	 */
	protected String documentNumber;

	/** 
	 * This attribute maps to the column type_Linking in the teacher table.
	 */
	protected String typeLinking;

	/** 
	 * This attribute maps to the column name_Specialty in the teacher table.
	 */
	protected String nameSpecialty;

	/**
	 * Method 'Teacher'
	 * 
	 */
	public Teacher()
	{
	}

	/**
	 * Method 'getIdDocument'
	 * 
	 * @return String
	 */
	public String getIdDocument()
	{
		return idDocument;
	}

	/**
	 * Method 'setIdDocument'
	 * 
	 * @param idDocument
	 */
	public void setIdDocument(String idDocument)
	{
		this.idDocument = idDocument;
	}

	/**
	 * Method 'getDocumentNumber'
	 * 
	 * @return String
	 */
	public String getDocumentNumber()
	{
		return documentNumber;
	}

	/**
	 * Method 'setDocumentNumber'
	 * 
	 * @param documentNumber
	 */
	public void setDocumentNumber(String documentNumber)
	{
		this.documentNumber = documentNumber;
	}

	/**
	 * Method 'getTypeLinking'
	 * 
	 * @return String
	 */
	public String getTypeLinking()
	{
		return typeLinking;
	}

	/**
	 * Method 'setTypeLinking'
	 * 
	 * @param typeLinking
	 */
	public void setTypeLinking(String typeLinking)
	{
		this.typeLinking = typeLinking;
	}

	/**
	 * Method 'getNameSpecialty'
	 * 
	 * @return String
	 */
	public String getNameSpecialty()
	{
		return nameSpecialty;
	}

	/**
	 * Method 'setNameSpecialty'
	 * 
	 * @param nameSpecialty
	 */
	public void setNameSpecialty(String nameSpecialty)
	{
		this.nameSpecialty = nameSpecialty;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Teacher)) {
			return false;
		}
		
		final Teacher _cast = (Teacher) _other;
		if (idDocument == null ? _cast.idDocument != idDocument : !idDocument.equals( _cast.idDocument )) {
			return false;
		}
		
		if (documentNumber == null ? _cast.documentNumber != documentNumber : !documentNumber.equals( _cast.documentNumber )) {
			return false;
		}
		
		if (typeLinking == null ? _cast.typeLinking != typeLinking : !typeLinking.equals( _cast.typeLinking )) {
			return false;
		}
		
		if (nameSpecialty == null ? _cast.nameSpecialty != nameSpecialty : !nameSpecialty.equals( _cast.nameSpecialty )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idDocument != null) {
			_hashCode = 29 * _hashCode + idDocument.hashCode();
		}
		
		if (documentNumber != null) {
			_hashCode = 29 * _hashCode + documentNumber.hashCode();
		}
		
		if (typeLinking != null) {
			_hashCode = 29 * _hashCode + typeLinking.hashCode();
		}
		
		if (nameSpecialty != null) {
			_hashCode = 29 * _hashCode + nameSpecialty.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TeacherPk
	 */
	public TeacherPk createPk()
	{
		return new TeacherPk(idDocument, documentNumber);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.Teacher: " );
		ret.append( "idDocument=" + idDocument );
		ret.append( ", documentNumber=" + documentNumber );
		ret.append( ", typeLinking=" + typeLinking );
		ret.append( ", nameSpecialty=" + nameSpecialty );
		return ret.toString();
	}

}
